import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { BadgeCheck, Check, Lock, ShieldCheck } from 'lucide-react'
import { PublicShell, Pill, Field, Input, Select, Table, Toggle, Steps, GoogleIcon } from '../ui'

const Wrap = ({children,className=''}) => <div className={`mx-auto max-w-6xl px-4 ${className}`}>{children}</div>

export function Account() {
  const [editing,setEditing]=useState(false)
  const [profile,setProfile]=useState({name:'Anand',star:'Rohini',gothra:'Bharadwaja',rashi:'Vrishabham (Taurus)',language:'English',address:'Kozhikode, Kerala, India',mobile:'+91 94966 86256',email:'anand@example.com'})
  const [draft,setDraft]=useState(profile)
  const [verify,setVerify]=useState(null)
  const [contact,setContact]=useState('')
  const [otp,setOtp]=useState('')
  const [notice,setNotice]=useState('')
  const [agentStatus,setAgentStatus]=useState(()=>sessionStorage.getItem('ta-agent-status')||'none')
  const [agentOpen,setAgentOpen]=useState(false)
  const [agentStep,setAgentStep]=useState(0)
  const [agent,setAgent]=useState({legalName:'Anand',address:'Kozhikode, Kerala, India',bankAccount:'',ifsc:'',bankName:'',upi:'',pan:'',aadhaar:''})
  const [docs,setDocs]=useState({photo:'',aadhaar:'',pan:'',bank:''})
  const [consent,setConsent]=useState(false)
  const googleLinked = true
  const flash = text => { setNotice(text); setTimeout(()=>setNotice(''),2200) }
  const saveProfile = () => { setProfile({...draft,mobile:profile.mobile,email:profile.email}); setEditing(false); flash('Profile details saved') }
  const startVerification = field => { setVerify({field,stage:'contact'}); setContact(profile[field]); setOtp('') }
  const sendOtp = () => { if(contact.trim()) { setVerify(v=>({...v,stage:'otp'})); flash(`Verification code sent to ${contact}`) } }
  const confirmContact = () => { if(otp.length<4) return; setProfile(p=>({...p,[verify.field]:contact})); setDraft(p=>({...p,[verify.field]:contact})); setVerify(null); flash('Contact verified and updated') }
  const beginAgent = () => { setAgentStatus('draft'); setAgentOpen(true); setAgentStep(0) }
  const setAgentField = (key,value) => setAgent(a=>({...a,[key]:value}))
  const selectDoc = (key,event) => setDocs(d=>({...d,[key]:event.target.files?.[0]?.name||''}))
  const agentMeta = {
    draft:['Draft','warn','Complete all KYC details and documents before submitting.','No staff feedback yet — this draft has not been submitted.'],
    review:['Under review','info','TempleAddress staff are reviewing your identity and bank documents.','KYC received. Initial review normally takes 2 working days.'],
    approved:['Approved','ok','Your agent account is active. You can now submit and manage temple listings.','Approved by Staff Moderator · Identity and bank details verified.'],
    rejected:['Changes requested','err','Correct the requested details and resubmit the application.','The bank copy is unclear. Upload a page showing your name, account number and IFSC.'],
  }
  const status = agentMeta[agentStatus]
  const kycReady = agent.legalName&&agent.address&&agent.bankAccount&&agent.ifsc&&agent.bankName&&agent.pan&&agent.aadhaar&&Object.values(docs).every(Boolean)&&consent
  const updateStatus = next => { setAgentStatus(next); sessionStorage.setItem('ta-agent-status',next); if(next==='review') setAgentOpen(false); flash(next==='review'?'Agent application submitted for staff review':`Application status: ${agentMeta[next][0]}`) }

  return <PublicShell><Wrap className="py-8">
    {notice&&<div className="fixed left-1/2 top-20 z-50 -translate-x-1/2 rounded-xl bg-brown-900 px-4 py-2 text-sm text-white shadow-soft">{notice}</div>}
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold">{profile.name}</h1><Pill tone="ok"><ShieldCheck size={12}/>Verified devotee</Pill></div><div className="mt-1 text-sm text-brown-500">{profile.mobile} · {profile.email} · {profile.language}</div></div><button onClick={()=>{setDraft(profile);setEditing(v=>!v)}} className="btn-g">{editing?'Close editor':'Edit profile'}</button></div>

    {editing&&<div className="card mt-6 overflow-hidden ring-1 ring-saffron-500/30"><div className="border-b border-brown-100 bg-brown-50 px-5 py-4"><h2 className="text-xl font-semibold">Edit profile</h2><p className="text-sm text-brown-500">These details prefill pooja bookings and receipts.</p></div><div className="grid gap-6 p-5 lg:grid-cols-[1fr_320px]"><div className="grid gap-4 sm:grid-cols-2">
      <Field label="Name"><Input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Preferred language"><Select value={draft.language} onChange={e=>setDraft({...draft,language:e.target.value})} options={['English','മലയാളം','Hindi']}/></Field>
      <Field label="Birth star / Nakshatra"><Select value={draft.star} onChange={e=>setDraft({...draft,star:e.target.value})} options={['Rohini','Makayiram','Thiruvathira','Punartham','Pooyam','Ayilyam']}/></Field><Field label="Gothra"><Input value={draft.gothra} onChange={e=>setDraft({...draft,gothra:e.target.value})}/></Field>
      <Field label="Rashi"><Select value={draft.rashi} onChange={e=>setDraft({...draft,rashi:e.target.value})} options={['Mesha (Aries)','Vrishabham (Taurus)','Mithunam (Gemini)','Karkidakam (Cancer)','Chingam (Leo)']}/></Field><Field label="Address" className="sm:col-span-2"><textarea className="input" rows={3} value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></Field>
      <div className="flex gap-2 sm:col-span-2"><button onClick={saveProfile} className="btn-p"><Check size={16}/>Save profile</button><button onClick={()=>setEditing(false)} className="btn-g">Cancel</button></div></div>
      <aside className="space-y-3"><div className="rounded-2xl border border-brown-100 p-4"><div className="flex items-center justify-between gap-2"><div><div className="text-xs font-semibold uppercase text-brown-500">Mobile number</div><b className="text-sm">{profile.mobile}</b></div><button onClick={()=>startVerification('mobile')} className="btn-g !px-3 !py-1.5 text-xs">Change</button></div><p className="mt-2 text-xs text-brown-500">The new mobile number must be verified by OTP.</p></div>
      <div className="rounded-2xl border border-brown-100 p-4"><div className="flex items-center justify-between gap-2"><div><div className="text-xs font-semibold uppercase text-brown-500">Email address</div><b className="text-sm">{profile.email}</b></div>{googleLinked?<Lock size={16} className="text-brown-400"/>:<button onClick={()=>startVerification('email')} className="btn-g !px-3 !py-1.5 text-xs">Change</button>}</div>{googleLinked?<p className="mt-2 text-xs text-blue-800"><GoogleIcon size={14} className="mr-1 inline"/>This email belongs to your linked Google account and cannot be changed here.</p>:<p className="mt-2 text-xs text-brown-500">The new email must be verified by OTP.</p>}</div>
      <div className="rounded-2xl bg-emerald-50 p-4 text-xs text-emerald-800"><b>Google account linked</b><p className="mt-1">The linked Google account cannot be edited or replaced in TempleAddress.</p></div></aside></div></div>}

    {verify&&<div className="fixed inset-0 z-50 grid place-items-center bg-brown-900/50 p-4" role="dialog" aria-modal="true"><div className="card w-full max-w-md p-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-saffron-50 text-saffron-600"><Lock size={18}/></span><div><h2 className="text-xl font-semibold">Verify new {verify.field==='mobile'?'mobile number':'email'}</h2><p className="text-sm text-brown-500">The existing contact stays active until verification succeeds.</p></div></div>{verify.stage==='contact'?<div className="mt-5 space-y-4"><Field label={verify.field==='mobile'?'New mobile number':'New email address'}><Input type={verify.field==='email'?'email':'tel'} value={contact} onChange={e=>setContact(e.target.value)}/></Field><button onClick={sendOtp} className="btn-p w-full">Send OTP</button></div>:<div className="mt-5 space-y-4"><div className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900">Code sent to <b>{contact}</b>.</div><Field label="6-digit OTP"><Input inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="••••••"/></Field><button onClick={confirmContact} className="btn-p w-full">Verify & update</button><button onClick={sendOtp} className="w-full text-sm font-semibold text-saffron-600">Resend code</button></div>}<button onClick={()=>setVerify(null)} className="btn-g mt-2 w-full">Cancel</button></div></div>}

    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><div className="card p-5"><h2 className="text-xl font-semibold">Upcoming</h2><div className="divide-y divide-brown-100">{[['Ganapathi Homam','Kottur Sree Mahavishnu Temple · Sat 13 Sept · Anand · Rohini','ok','Confirmed'],['Ashta Dravya Maha Ganapathi Homam','Special pooja · 14 Sept · proof pending','warn','Booked']].map(([a,b,t,s])=><div key={a} className="flex items-center gap-3 py-3"><div className="flex-1"><b>{a}</b><div className="text-sm text-brown-500">{b}</div></div><Pill tone={t}>{s}</Pill><Link to="/receipt" className="btn-g !py-1.5">Receipt</Link></div>)}</div><p className="mt-2 text-xs text-brown-500">Cancel or reschedule until the chart closes (12 Sept, 8:00 PM).</p></div><div className="card p-5"><h2 className="text-xl font-semibold">Past receipts</h2><Table head={['Date','Temple','Item','Amount','']} rows={[["31 Jul","Perayattil Subrahmanya Temple","Pushpanjali × 2","₹40",<Link to="/receipt" className="text-saffron-600">PDF</Link>],["5 Jun","Kottur Sree Mahavishnu Temple","Donation (80G)","₹1,000",<Link to="/receipt" className="text-saffron-600">PDF · 80G</Link>]]}/></div></div>
      <aside className="space-y-4"><div className="card p-5"><h3 className="font-semibold">Quick book</h3><Link to="/book/kottur-sree-mahavishnu-temple" className="btn-p mt-2 w-full">Kottur Mahavishnu Temple</Link><Link to="/temples" className="btn-s mt-2 w-full">Another temple</Link></div><div className="card p-5 text-sm"><h3 className="font-semibold">Family members</h3><div className="mt-2 space-y-1"><div>{profile.name} · {profile.star}</div><div>Devi · Makayiram</div><div>Aarav · Thiruvathira</div></div><button className="text-saffron-600">+ Add</button></div><div className="card space-y-2 p-5"><h3 className="font-semibold">Notifications</h3><Toggle label="WhatsApp" defaultChecked/><Toggle label="Email" defaultChecked/></div></aside></div>

    <section className="mt-6 overflow-hidden rounded-3xl bg-brown-900 text-white"><div className="grid gap-6 p-6 md:grid-cols-[1fr_auto] md:items-center md:p-8"><div><div className="flex flex-wrap gap-2"><Pill tone="gold"><BadgeCheck size={12}/>TempleAddress partner network</Pill>{status&&<Pill tone={status[1]}>{status[0]}</Pill>}</div><h2 className="mt-3 text-2xl font-semibold">{agentStatus==='approved'?'Your verified agent profile':'Become a TempleAddress agent'}</h2><p className="mt-2 max-w-2xl text-sm text-brown-100">{agentStatus==='approved'?'View your agent identity, territory, referral activity and KYC status.':'Help temples create verified digital pages and earn referral rewards. KYC and bank details are reviewed before activation.'}</p></div>{agentStatus==='none'?<Link to="/account/agent-application" onClick={()=>sessionStorage.setItem('ta-agent-status','draft')} className="btn-p">Apply to become an agent</Link>:agentStatus==='draft'||agentStatus==='rejected'?<Link to="/account/agent-application" className="btn bg-white text-brown-900">{agentStatus==='draft'?'Continue application':'Fix & resubmit'}</Link>:agentStatus==='approved'?<Link to="/agent" className="btn-p">Agent profile</Link>:null}</div></section>
    {status&&<div className="card mt-4 p-5"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">Agent application</h3><Pill tone={status[1]}>{status[0]}</Pill><span className="ml-auto text-xs text-brown-500">TA-AG-2026-0184 · Updated 11 Sept 2026</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-brown-50 p-3 text-sm">{status[2]}</div><div className={`rounded-xl p-3 text-sm ${agentStatus==='rejected'?'bg-red-50 text-red-800':agentStatus==='approved'?'bg-emerald-50 text-emerald-800':'bg-blue-50 text-blue-900'}`}><b>Admin / staff feedback</b><p className="mt-1">{status[3]}</p></div></div><div className="mt-4 flex flex-wrap items-center gap-2 text-xs"><b className="text-brown-500">Prototype status preview:</b>{['draft','review','approved','rejected'].map(s=><button key={s} onClick={()=>updateStatus(s)} className={`rounded-full px-2.5 py-1 font-semibold ${agentStatus===s?'bg-brown-900 text-white':'bg-brown-100 text-brown-600'}`}>{agentMeta[s][0]}</button>)}</div></div>}

    {agentOpen&&<div className="fixed inset-0 z-50 overflow-y-auto bg-brown-900/60 p-4"><div className="mx-auto my-6 max-w-3xl overflow-hidden rounded-2xl bg-brown-50 shadow-soft"><div className="flex justify-between gap-3 bg-brown-900 px-6 py-5 text-white"><div><h2 className="text-2xl font-semibold">Agent KYC application</h2><p className="text-sm text-brown-100">Saved as draft until submitted for staff verification.</p></div><button onClick={()=>setAgentOpen(false)} className="text-2xl" aria-label="Close">×</button></div><div className="p-6"><Steps items={['KYC details','Documents','Review']} at={agentStep}/>
      {agentStep===0&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Legal name" hint="Must match PAN and Aadhaar"><Input value={agent.legalName} onChange={e=>setAgentField('legalName',e.target.value)}/></Field><Field label="PAN card number"><Input value={agent.pan} onChange={e=>setAgentField('pan',e.target.value.toUpperCase())} placeholder="ABCDE1234F" maxLength={10}/></Field><Field label="Aadhaar number"><Input value={agent.aadhaar} onChange={e=>setAgentField('aadhaar',e.target.value)} placeholder="XXXX XXXX XXXX"/></Field><Field label="UPI ID (optional)"><Input value={agent.upi} onChange={e=>setAgentField('upi',e.target.value)} placeholder="name@bank"/></Field><Field label="Full address" className="sm:col-span-2"><textarea className="input" rows={3} value={agent.address} onChange={e=>setAgentField('address',e.target.value)}/></Field><Field label="Bank account number"><Input value={agent.bankAccount} onChange={e=>setAgentField('bankAccount',e.target.value)}/></Field><Field label="IFSC"><Input value={agent.ifsc} onChange={e=>setAgentField('ifsc',e.target.value.toUpperCase())}/></Field><Field label="Bank name" className="sm:col-span-2"><Input value={agent.bankName} onChange={e=>setAgentField('bankName',e.target.value)}/></Field></div>}
      {agentStep===1&&<div><div className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900"><Lock size={14} className="mr-1 inline"/>Files are visible only to authorised KYC reviewers.</div><div className="mt-4 grid gap-4 sm:grid-cols-2">{[['photo','Your recent photo','JPG or PNG'],['aadhaar','Aadhaar copy','Front and back'],['pan','PAN card copy','PDF, JPG or PNG'],['bank','Bank passbook / statement','Must show account details']].map(([key,label,hint])=><Field key={key} label={label} hint={docs[key]?`Selected: ${docs[key]}`:hint}><Input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>selectDoc(key,e)}/></Field>)}</div></div>}
      {agentStep===2&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-4 shadow-ring"><div className="text-xs font-semibold uppercase text-brown-500">Applicant</div><b>{agent.legalName||'Not entered'}</b><p className="text-sm text-brown-500">{agent.address||'Address not entered'}</p><p className="mt-2 text-sm">PAN: {agent.pan||'—'} · Aadhaar: {agent.aadhaar?'Provided':'—'}</p></div><div className="rounded-xl bg-white p-4 shadow-ring"><div className="text-xs font-semibold uppercase text-brown-500">Settlement</div><b>{agent.bankName||'Bank not entered'}</b><p className="text-sm text-brown-500">A/c {agent.bankAccount||'—'} · {agent.ifsc||'IFSC —'}</p><p className="mt-2 text-sm">UPI: {agent.upi||'Not provided'}</p></div></div><div className="rounded-xl bg-white p-4 shadow-ring"><b>Documents</b><div className="mt-2 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">{[['Photo','photo'],['Aadhaar','aadhaar'],['PAN card','pan'],['Bank proof','bank']].map(([label,key])=><span key={key} className={docs[key]?'text-emerald-700':'text-red-600'}>{docs[key]?'✓':'○'} {label}</span>)}</div></div><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/>I confirm these details are correct and consent to KYC verification.</label>{!kycReady&&<p className="rounded-xl bg-saffron-50 p-3 text-xs text-saffron-800">Complete every required KYC field, upload all four documents, and confirm consent before submitting.</p>}</div>}
      <div className="mt-6 flex flex-wrap justify-between gap-2"><button onClick={()=>{setAgentStatus('draft');setAgentOpen(false);flash('Application saved as draft')}} className="btn-g">Save draft & close</button><div className="flex gap-2">{agentStep>0&&<button onClick={()=>setAgentStep(s=>s-1)} className="btn-g">Back</button>}{agentStep<2?<button onClick={()=>setAgentStep(s=>s+1)} className="btn-p">Continue</button>:<button disabled={!kycReady} onClick={()=>updateStatus('review')} className="btn-p"><ShieldCheck size={16}/>Submit for review</button>}</div></div></div></div></div>}
  </Wrap></PublicShell>
}

export function AgentApplication() {
  const nav = useNavigate()
  const [step,setStep]=useState(0)
  const [notice,setNotice]=useState('')
  const [consent,setConsent]=useState(false)
  const [agent,setAgent]=useState({legalName:'Anand',address:'Kozhikode, Kerala, India',bankAccount:'',ifsc:'',bankName:'',upi:'',pan:'',aadhaar:''})
  const [docs,setDocs]=useState({photo:'',aadhaar:'',pan:'',bank:''})
  const setField = (key,value) => setAgent(a=>({...a,[key]:value}))
  const selectDoc = (key,event) => setDocs(d=>({...d,[key]:event.target.files?.[0]?.name||''}))
  const detailsReady = agent.legalName&&agent.address&&agent.bankAccount&&agent.ifsc&&agent.bankName&&agent.pan&&agent.aadhaar
  const documentsReady = Object.values(docs).every(Boolean)
  const ready = detailsReady&&documentsReady&&consent
  const saveDraft = () => { sessionStorage.setItem('ta-agent-status','draft'); nav('/account') }
  const submit = () => {
    if(!ready) { setNotice('Complete all required details and documents before submitting.'); return }
    sessionStorage.setItem('ta-agent-status','review')
    nav('/account')
  }

  return <PublicShell hideChatbot><Wrap className="max-w-4xl py-6 sm:py-10">
    <Link to="/account" className="inline-flex items-center gap-1 text-sm font-semibold text-brown-500 hover:text-saffron-600">← Back to my account</Link>
    <div className="mt-4 overflow-hidden rounded-3xl bg-brown-900 px-5 py-7 text-white sm:px-8 sm:py-9"><Pill tone="gold"><BadgeCheck size={12}/>Agent application</Pill><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Agent KYC verification</h1><p className="mt-2 max-w-2xl text-sm text-brown-100">Complete this form at your own pace. It remains a draft until you submit it to TempleAddress staff.</p></div>

    <div className="card mt-5 p-4 sm:p-7"><Steps items={['KYC details','Documents','Review']} at={step}/>
      {step===0&&<div><div className="mb-5"><h2 className="text-xl font-semibold">Personal and settlement details</h2><p className="text-sm text-brown-500">Use the same legal name shown on your PAN and bank account.</p></div><div className="grid gap-4 sm:grid-cols-2">
        <Field label="Legal name" hint="Must match PAN and Aadhaar"><Input value={agent.legalName} onChange={e=>setField('legalName',e.target.value)}/></Field>
        <Field label="PAN card number"><Input value={agent.pan} onChange={e=>setField('pan',e.target.value.toUpperCase())} placeholder="ABCDE1234F" maxLength={10}/></Field>
        <Field label="Aadhaar number"><Input value={agent.aadhaar} onChange={e=>setField('aadhaar',e.target.value)} placeholder="XXXX XXXX XXXX" inputMode="numeric"/></Field>
        <Field label="UPI ID (optional)"><Input value={agent.upi} onChange={e=>setField('upi',e.target.value)} placeholder="name@bank"/></Field>
        <Field label="Full address" className="sm:col-span-2"><textarea className="input" rows={4} value={agent.address} onChange={e=>setField('address',e.target.value)}/></Field>
        <Field label="Bank account number"><Input value={agent.bankAccount} onChange={e=>setField('bankAccount',e.target.value)} inputMode="numeric"/></Field>
        <Field label="IFSC"><Input value={agent.ifsc} onChange={e=>setField('ifsc',e.target.value.toUpperCase())} placeholder="FDRL0001234"/></Field>
        <Field label="Bank name" className="sm:col-span-2"><Input value={agent.bankName} onChange={e=>setField('bankName',e.target.value)}/></Field>
      </div></div>}

      {step===1&&<div><div className="mb-5"><h2 className="text-xl font-semibold">KYC documents</h2><p className="text-sm text-brown-500">Upload clear copies. PDF, JPG and PNG files are accepted.</p></div><div className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900"><Lock size={14} className="mr-1 inline"/>These files are visible only to authorised KYC reviewers.</div><div className="mt-4 grid gap-4 sm:grid-cols-2">
        {[['photo','Your recent photo','A clear portrait photo'],['aadhaar','Aadhaar copy','Front and back in one file'],['pan','PAN card copy','The card must be readable'],['bank','Bank passbook or statement','Must show name, account number and IFSC']].map(([key,label,hint])=><label key={key} className={`block rounded-2xl border-2 border-dashed p-4 ${docs[key]?'border-emerald-300 bg-emerald-50':'border-brown-200 bg-white'}`}><span className="font-semibold">{docs[key]?'✓ ':''}{label}</span><span className="mt-1 block text-xs text-brown-500">{docs[key]||hint}</span><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>selectDoc(key,e)} className="mt-3 block w-full text-xs"/></label>)}
      </div></div>}

      {step===2&&<div><div className="mb-5"><h2 className="text-xl font-semibold">Review and submit</h2><p className="text-sm text-brown-500">Check your information before sending it to staff.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-brown-50 p-4"><div className="text-xs font-semibold uppercase text-brown-500">Applicant</div><b>{agent.legalName||'Not entered'}</b><p className="text-sm text-brown-500">{agent.address||'Address not entered'}</p><p className="mt-2 text-sm">PAN: {agent.pan||'—'}<br/>Aadhaar: {agent.aadhaar?'Provided':'—'}</p></div><div className="rounded-2xl bg-brown-50 p-4"><div className="text-xs font-semibold uppercase text-brown-500">Settlement</div><b>{agent.bankName||'Bank not entered'}</b><p className="text-sm text-brown-500">A/c {agent.bankAccount||'—'}<br/>{agent.ifsc||'IFSC —'}</p><p className="mt-2 text-sm">UPI: {agent.upi||'Not provided'}</p></div></div>
        <div className="mt-4 rounded-2xl border border-brown-100 p-4"><b>Documents</b><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">{[['Photo','photo'],['Aadhaar','aadhaar'],['PAN card','pan'],['Bank proof','bank']].map(([label,key])=><span key={key} className={docs[key]?'text-emerald-700':'text-red-600'}>{docs[key]?'✓':'○'} {label}</span>)}</div></div>
        <label className="mt-4 flex items-start gap-3 rounded-2xl bg-brown-50 p-4 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 h-4 w-4"/><span>I confirm these details are correct and consent to KYC verification by authorised TempleAddress staff.</span></label>
        {(!ready||notice)&&<p className="mt-4 rounded-xl bg-saffron-50 p-3 text-sm text-saffron-800">{notice||'Complete all required fields, upload all four documents, and confirm consent before submitting.'}</p>}
      </div>}

      <div className="mt-7 flex flex-col-reverse gap-3 border-t border-brown-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><button onClick={saveDraft} className="btn-g">Save draft & return</button><div className="flex gap-2">{step>0&&<button onClick={()=>{setNotice('');setStep(s=>s-1)}} className="btn-g flex-1 sm:flex-none">Back</button>}{step<2?<button onClick={()=>setStep(s=>s+1)} className="btn-p flex-1 sm:flex-none">Continue</button>:<button disabled={!ready} onClick={submit} className="btn-p flex-1 sm:flex-none"><ShieldCheck size={16}/>Submit for review</button>}</div></div>
    </div>
    <p className="mt-4 px-2 text-center text-xs text-brown-500">Your application ID will be generated after submission. Review status and staff feedback appear on your account page.</p>
  </Wrap></PublicShell>
}
