import React, { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { temples } from '../data'
import { PublicShell, Field, Input, Money, Steps } from '../ui'
import { bookingKey, readBookings, indiaDate, unavailable } from '../booking'

const stars = ['Aswathi','Bharani','Karthika','Rohini','Makayiram','Thiruvathira','Punartham','Pooyam','Ayilyam','Makam','Pooram','Uthram','Atham','Chithira','Chothi','Vishakham','Anizham','Thrikketta','Moolam','Pooradam','Uthradam','Thiruvonam','Avittam','Chathayam','Pooruruttathi','Uthrattathi','Revathi']
const rashis = ['Mesha','Vrishabha','Mithuna','Karka','Simha','Kanya','Tula','Vrischika','Dhanu','Makara','Kumbha','Meena']
const Wrap = ({children}) => <div translate="no" className="notranslate mx-auto max-w-3xl space-y-5 px-4 py-8">{children}</div>
const Amount = ({label,value}) => <div className="flex justify-between gap-4 border-b border-brown-100 py-2"><span>{label}</span><Money v={value}/></div>
export function Booking() {
  const {slug} = useParams(); const [query] = useSearchParams(); const navigate = useNavigate()
  const temple = temples.find(t => t.slug === slug)
  const [code,setCode] = useState(query.get('pooja') || temple?.poojas[0]?.code)
  const pooja = temple?.poojas.find(p => p.code === code)
  const [step,setStep] = useState(0), [date,setDate] = useState(indiaDate()), [quantity,setQuantity] = useState(1)
  const [recurring,setRecurring] = useState(false), [nextDate,setNextDate] = useState('')
  const [name,setName] = useState(''), [kind,setKind] = useState('Nakshatra'), [ritual,setRitual] = useState('')
  const [mobile,setMobile] = useState(''), [country,setCountry] = useState('+91'), [donation,setDonation] = useState('0'), [notes,setNotes] = useState('')
  const [otp,setOtp] = useState(''), [cooldown,setCooldown] = useState(0), [sentAt,setSentAt] = useState(0)
  const [error,setError] = useState(''), [gateway,setGateway] = useState('Razorpay'), [outcome,setOutcome] = useState('success'), [gatewayOpen,setGatewayOpen] = useState(false), [processing,setProcessing] = useState(false), [result,setResult] = useState('')
  const [bookingCode] = useState(() => `TPB-${crypto.randomUUID()}`)
  const timer = useRef(); const busy = useRef(false)
  useEffect(() => () => clearTimeout(timer.current), [])
  useEffect(() => { if (!cooldown) return; const id = setTimeout(() => setCooldown(cooldown - 1),1000); return () => clearTimeout(id) },[cooldown])
  if (!temple || !pooja) return <PublicShell><Wrap><h1>Temple or pooja not found</h1><Link to="/temples" className="btn-p">Browse temples</Link></Wrap></PublicShell>
  const dates = recurring ? [date,nextDate] : [date]
  const donationValue = Number(donation)
  const subtotal = pooja.price * quantity * dates.length, total = subtotal + (Number.isFinite(donationValue) ? donationValue : 0)
  const fee = Math.round(total * 0.02 * 100) / 100, feeTax = Math.round(fee * 0.18 * 100) / 100
  const availability = () => dates.map(d => unavailable(temple,pooja,d,quantity,readBookings())).find(Boolean) || (recurring && nextDate <= date ? 'Next recurring date must be after the first date.' : '')
  const blocked = availability()
  const proceed = e => { e.preventDefault(); setError(''); if (blocked) return setError(blocked); setStep(step + 1) }
  const sendOtp = e => { e?.preventDefault(); const valid = country === '+91' ? /^\d{10}$/.test(mobile) : /^\d{7,12}$/.test(mobile); if (!valid) return setError('Enter a valid mobile number without the country code.'); if (!Number.isFinite(donationValue) || donationValue < 0) return setError('Enter a valid donation amount.'); setError(''); setOtp(''); setSentAt(Date.now()); setCooldown(30); setStep(2) }
  const pay = () => {
    if (busy.current) return
    const reason = availability(); if (reason) {setGatewayOpen(false); setError(reason); setStep(0); return}
    busy.current = true; setProcessing(true)
    timer.current = setTimeout(() => {
      busy.current = false; setProcessing(false); setGatewayOpen(false)
      if (outcome !== 'success') {setResult(outcome); return}
      const record = {bookingCode,status:'paid',createdAt:new Date().toISOString(),temple:temple.name,templeCode:temple.code,slug:temple.slug,address:temple.address,pooja:pooja.name,poojaCode:pooja.code,unitPrice:pooja.price,quantity,dates,slot:`${pooja.startTime} – ${pooja.endTime} IST`,name,mobile:`${country}${mobile}`,kind,ritual,donation:donationValue,notes,subtotal,total,gateway,fee,feeTax,paid:Math.round((total+fee+feeTax)*100)/100,transactionId:`demo_${crypto.randomUUID()}`}
      try { const existing = readBookings(); sessionStorage.setItem(bookingKey,JSON.stringify([...existing.filter(r => r.bookingCode !== bookingCode),record])); navigate(`/receipt/${bookingCode}`) } catch {setError('Unable to save this demo receipt. Enable session storage and retry. No real payment was taken.')}
    },1200)
  }
  return <PublicShell><Wrap><Link to={`/t/${slug}`}>← {temple.name}</Link><h1 className="text-3xl font-semibold">Book a pooja</h1><p className="rounded-xl bg-blue-50 p-3 text-sm">Demo checkout — OTP and payments are simulated. No SMS or money is sent. All times are India Standard Time.</p><Steps items={['Pooja','Devotee','Verify','Summary']} at={step}/>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    {step === 0 && <form onSubmit={proceed} className="card space-y-4 p-6"><Field label="Pooja"><select className="input" value={code} onChange={e => setCode(e.target.value)}>{temple.poojas.map(p => <option key={p.code} value={p.code}>{p.name} — ₹{p.price}{p.bookingType === 'Offline' ? ' · Offline only' : ''}</option>)}</select></Field><Field label="Pooja date"><Input required type="date" min={indiaDate()} value={date} onChange={e => setDate(e.target.value)}/></Field><Field label="Time slot (IST)"><select className="input" aria-describedby="availability" disabled={!!blocked}><option>{pooja.startTime} – {pooja.endTime}{blocked ? ' · Unavailable' : ' · Available'}</option></select></Field><p className="text-sm text-brown-500">{pooja.minBookingTime}{pooja.dailyLimit > 0 && ` · Daily capacity: ${pooja.dailyLimit}`}</p><Field label="Quantity"><Input required type="number" min="1" max="100" step="1" value={quantity} onChange={e => setQuantity(Number(e.target.value))}/></Field><label className="flex gap-2"><input type="checkbox" checked={recurring} onChange={e => setRecurring(e.target.checked)}/>Recurring booking</label>{recurring && <Field label="Next recurring date" hint="One additional occurrence is included in this payment. No automatic debit."><Input required type="date" min={date} value={nextDate} onChange={e => setNextDate(e.target.value)}/></Field>}<p id="availability" role="status" className={blocked ? 'text-red-700' : 'text-emerald-700'}>{blocked || 'Selected date and time available in this demo.'}</p><Amount label="Pooja total" value={subtotal}/><button disabled={!!blocked} className="btn-p w-full disabled:opacity-40">Continue</button></form>}
    {step === 1 && <form onSubmit={sendOtp} className="card space-y-4 p-6"><Field label="Devotee full name"><Input required value={name} onChange={e => setName(e.target.value)} maxLength={120}/></Field><fieldset><legend className="label">Ritual information</legend><div className="flex flex-wrap gap-4">{['Nakshatra','Gothra','Rashi'].map(k => <label key={k} className="flex gap-2"><input type="radio" name="ritual" checked={kind === k} onChange={() => {setKind(k);setRitual('')}}/>{k}</label>)}</div></fieldset><Field label={kind}>{kind === 'Gothra' ? <Input required value={ritual} onChange={e => setRitual(e.target.value)} placeholder="Enter Gothra"/> : <select required className="input" value={ritual} onChange={e => setRitual(e.target.value)}><option value="">Select {kind}</option>{(kind === 'Nakshatra' ? stars : rashis).map(s => <option key={s}>{s}</option>)}</select>}</Field><div className="grid gap-3 sm:grid-cols-[160px_1fr]"><Field label="Country code"><select className="input" value={country} onChange={e => setCountry(e.target.value)}>{['+91','+971','+968','+1','+44'].map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Mobile number (OTP required)"><Input required type="tel" inputMode="numeric" value={mobile} onChange={e => setMobile(e.target.value.replace(/\D/g,''))} maxLength={12}/></Field></div><Field label="Temple donation (optional)"><Input type="number" min="0" max="1000000" step="0.01" value={donation} onChange={e => setDonation(e.target.value)}/></Field><Field label="Special instructions (optional)"><textarea className="input" value={notes} onChange={e => setNotes(e.target.value)} maxLength={1000}/></Field><Amount label="Pooja total" value={subtotal}/><Amount label="Donation" value={donationValue || 0}/><Amount label="Booking total" value={total}/><div className="flex gap-2"><button type="button" className="btn-g" onClick={() => setStep(0)}>Back</button><button className="btn-p">Verify phone with OTP</button></div></form>}
    {step === 2 && <form className="card space-y-4 p-6" onSubmit={e => {e.preventDefault();if (otp !== '123456' || Date.now()-sentAt > 300000) return setError('Incorrect or expired OTP. Request a new demo code.');setError('');setStep(3)}}><h2 className="text-xl font-semibold">Verify your mobile</h2><p>Verify {country} ••••••{mobile.slice(-4)}. Demo OTP: <b>123456</b> (valid for 5 minutes).</p><Field label="6-digit OTP"><Input required inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" value={otp} onChange={e => setOtp(e.target.value)}/></Field><button className="btn-p">Verify & continue</button><button type="button" className="btn-g ml-2" disabled={cooldown > 0} onClick={() => sendOtp()}>{cooldown ? `Resend in ${cooldown}s` : 'Resend OTP'}</button><button type="button" className="block underline" onClick={() => {setError('');setStep(1)}}>Change details</button></form>}
    {step === 3 && <div className="card space-y-4 p-6"><h2 className="text-xl font-semibold">Booking summary</h2><p className="break-all text-sm">Booking number: {bookingCode}</p><p>{temple.name} · {temple.code}</p><p>{name} · {kind}: {ritual}<br/>{country}{mobile} · Verified in demo</p>{dates.map(d => <Amount key={d} label={`${pooja.name} × ${quantity} · ${d} · ${pooja.startTime}–${pooja.endTime} IST`} value={pooja.price * quantity}/>)}{notes && <p>Instructions: {notes}</p>}<Amount label="Donation" value={donationValue}/><Amount label="Booking total" value={total}/><p className="text-sm text-brown-500">Gateway processing charges are shown separately inside the gateway checkout.</p><Field label="Payment gateway"><select className="input" value={gateway} onChange={e => setGateway(e.target.value)}>{['Razorpay','Omniware / Federal Bank','Stripe'].map(g => <option key={g}>{g}</option>)}</select></Field>{result && <div role="alert" className="rounded-xl bg-red-50 p-4"><b>{result === 'failed' ? 'Payment failed' : 'Gateway timed out'}</b><p>No booking is confirmed. This is a simulation; no money was taken. Retry the same booking below.</p></div>}<div className="flex gap-2"><button className="btn-g" onClick={() => {setResult('');setStep(1)}}>Edit details</button><button className="btn-p" onClick={() => {const reason = availability();if(reason){setError(reason);setStep(0)}else setGatewayOpen(true)}}>{result ? 'Retry payment' : `Pay ₹${total}`}</button></div></div>}
    {gatewayOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-label="Simulated payment gateway"><div className="card w-full max-w-lg space-y-4 p-6"><h2 className="text-xl font-semibold">{gateway} · Test mode</h2><p>No real card or bank details required.</p><Amount label="Booking amount" value={total}/><Amount label="Demo gateway fee (2%)" value={fee}/><Amount label="GST on gateway fee (18%)" value={feeTax}/><Amount label="Total charged by gateway" value={Math.round((total + fee + feeTax)*100)/100}/><Field label="Simulate outcome"><select disabled={processing} className="input" value={outcome} onChange={e => setOutcome(e.target.value)}><option value="success">Success</option><option value="failed">Payment failed</option><option value="timeout">Gateway timeout</option></select></Field><button className="btn-p" disabled={processing} onClick={pay}>{processing ? 'Processing…' : 'Simulate payment'}</button><button className="btn-g ml-2" disabled={processing} onClick={() => setGatewayOpen(false)}>Cancel</button></div></div>}
  </Wrap></PublicShell>
}
export function BookingReceipt() {
  const {bookingCode} = useParams(); const record = readBookings().find(r => r.bookingCode === bookingCode && r.status === 'paid')
  if (!record) return <PublicShell><Wrap><h1>Receipt unavailable</h1><p>Only successful demo payments have receipts, saved in this browser session.</p><Link to="/temples">Browse temples</Link></Wrap></PublicShell>
  return <PublicShell hideChatbot><Wrap><div className="print:hidden flex gap-3"><button className="btn-p" onClick={() => window.print()}>Print / Save PDF</button><Link className="btn-g" to={`/book/${record.slug}`}>Book again</Link></div><article id="booking-receipt" className="card space-y-4 p-6"><p className="font-bold text-emerald-700">CONFIRMED · DEMO RECEIPT</p><h1 className="text-2xl font-semibold">{record.temple}</h1><p>{record.address}</p><h2 className="text-xl">Booking receipt</h2><p className="break-all">Booking number: {record.bookingCode}</p><p>Temple code: {record.templeCode}<br/>Booked: {new Date(record.createdAt).toLocaleString()}<br/>Devotee: {record.name} · {record.kind}: {record.ritual}<br/>Mobile: {record.mobile}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Pooja','Date / time','Qty','Amount'].map(h => <th className="th" key={h}>{h}</th>)}</tr></thead><tbody>{record.dates.map(d => <tr key={d}><td className="td">{record.pooja}</td><td className="td">{d}<br/>{record.slot}</td><td className="td">{record.quantity}</td><td className="td"><Money v={record.unitPrice * record.quantity}/></td></tr>)}</tbody></table></div><Amount label="Pooja subtotal" value={record.subtotal}/><Amount label="Temple donation" value={record.donation}/><Amount label="Temple booking total" value={record.total}/><Amount label="Gateway fee" value={record.fee}/><Amount label="GST on gateway fee" value={record.feeTax}/><Amount label="Total simulated payment" value={record.paid}/><p className="break-all">Gateway: {record.gateway}<br/>Transaction ID: {record.transactionId}</p>{record.notes && <p>Instructions: {record.notes}</p>}<p className="text-sm text-brown-500">No real payment collected. Not a tax invoice or an 80G certificate. Notifications are not sent in this demo.</p></article></Wrap></PublicShell>
}
