import React, { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Wallet, Share2, PlusCircle, ListChecks, Map, Users, BarChart3, Inbox, ShieldCheck, CalendarCheck, Sparkles, Landmark, Banknote, HandCoins, Database, Settings2, Table2, ArrowRightLeft, Download, Upload, Check, Copy, Smartphone, MessageCircle, Globe, TrendingUp } from 'lucide-react'
import { LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts'
import { temples, analytics } from '../data'
import { DashShell, Pill, Field, Input, Select, Toggle, Table, Stat, Tabs, Steps, useToast } from '../ui'

const H = ({ t, s, right }) => <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t}</h1>{s&&<div className="text-sm text-brown-500">{s}</div>}</div>{right}</div>

/* ================= AGENT ================= */
const agentItems=[{group:'Agent',links:[['/agent','Wallet',Wallet],['/agent/share','Share',Share2],['/agent/submit','Add temple',PlusCircle],['/agent/submissions','Submissions',ListChecks]]}]
const AShell = ({children}) => <DashShell role="Agent" user="Jinsha · JIN-4471 · Kozhikode North" items={agentItems}>{children}</DashShell>

export function AWallet() {
  const [wd,setWd]=useState(false); const [toast,el]=useToast()
  return (<AShell>{el}<H t="Wallet" s="Agent code JIN-4471 · Dealer: Kozhikode North (Rahul)" right={<button onClick={()=>setWd(!wd)} className="btn-p"><Banknote size={16}/>Withdraw</button>}/>
    <div className="grid grid-cols-3 gap-3"><Stat v="₹6,840" l="available"/><Stat v="₹2,250" l="pending approval"/><Stat v="₹21,500" l="withdrawn so far"/></div>
    {wd && <div className="card mt-5 p-5"><h3 className="font-semibold">Withdraw to bank / UPI</h3><div className="mt-3 grid gap-4 md:grid-cols-2"><Field label="Amount ₹" hint="Minimum ₹500 · paid in the monthly cycle (next: 30 Sept)"><Input type="number" defaultValue="6840"/></Field><Field label="Pay to"><Select options={['UPI jinsha@okaxis','Federal Bank ····8821']}/></Field></div><p className="text-xs text-brown-500">TDS may be deducted as per rules; you'll get a statement.</p><button onClick={()=>{toast('Withdrawal of ₹6,840 requested');setWd(false)}} className="btn-p mt-3">Request ₹6,840</button></div>}
    <div className="card mt-5 p-5"><h3 className="font-semibold">Ledger</h3><Table head={['Date','For','Type','₹','Status']} rows={[['11 Sept','Resurge India Foundation → Kottur (Patron ₹30,000)','Sponsorship 15%','4,500',<Pill tone="ok">Approved</Pill>],['9 Sept','Vengamala Bhagavathi Temple','KYC done, bookings on','200',<Pill tone="ok">Approved</Pill>],['9 Sept','Vengamala Bhagavathi Temple','Listing approved','100',<Pill tone="ok">Approved</Pill>],['8 Sept','Special pooja via share link (×3)','5% of ₹4,500','225',<Pill tone="warn">Pending 15-day window</Pill>],['4 Sept','Prasad Nambeesan — Service Pro','15% of ₹3,000','450',<Pill tone="ok">Approved</Pill>],['2 Sept','Thrikapaleshwaram — Basic plan','15% of ₹6,000','900',<Pill tone="warn">Pending</Pill>],['30 Aug','Withdrawal · UTR FDRLN26242…','Paid out','−5,000',<Pill tone="ok">Paid</Pill>]]}/></div>
    <div className="card mt-5 p-5 text-sm"><b>Territory rates (Kozhikode North)</b><div className="text-brown-500">Listing approved ₹100 · KYC ₹200 · Plan 15% · Sponsorship 15% · Renewal 5% · Special pooja via your link 5% · Fee revenue from your listings 10% for 12 months</div></div></AShell>)
}
export function AShare() {
  const [toast,el]=useToast()
  return (<AShell>{el}<H t="Share & promote" s="Every link carries your code JIN-4471 · 30-day attribution"/>
    <div className="card p-5"><Field label="What to share"><Select options={['Kottur Sree Mahavishnu Temple','Special: Ashta Dravya Maha Ganapathi Homam · 14 Sept','Sponsor a temple','Vengamala Bhagavathi Temple']}/></Field><div className="mt-2 flex items-center gap-2 rounded-xl bg-brown-50 px-3 py-2"><code className="flex-1 text-sm">https://kottur.templeaddress.com/?ref=JIN-4471</code><button onClick={()=>toast('Copied')} className="btn-g !py-1.5"><Copy size={14}/>Copy</button></div>
      <div className="mt-3 flex flex-wrap gap-2"><button className="btn-wa"><MessageCircle size={16}/>WhatsApp</button><button className="btn-s">Facebook</button><button className="btn-s">Instagram story</button><button className="btn-g">X</button><button className="btn-g"><Share2 size={16}/>Share…</button></div></div>
    <div className="mt-5 grid gap-5 md:grid-cols-2"><div className="card p-5"><h3 className="font-semibold">Poster for WhatsApp status</h3><div className="photo mt-2 aspect-[9/16] max-w-[200px] rounded-xl p-3 text-xs text-white">Kottur Sree Mahavishnu Temple<br/>Book pooja online<br/>QR · JIN-4471</div><button className="btn-g mt-2"><Download size={16}/>Download poster</button></div>
      <div className="card p-5"><h3 className="font-semibold">Pre-filled message</h3><textarea rows={6} className="input mt-2" defaultValue={'🙏 Kottur Sree Mahavishnu Temple is now online. Book Ganapathi Homam, Pushpanjali and more — receipt on WhatsApp, 100% goes to the temple.\nkottur.templeaddress.com/?ref=JIN-4471'}/><span className="text-xs text-brown-500">Malayalam version available</span></div></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Results this month</h3><Table head={['Link','Clicks','Bookings','Plans / sponsors','Earned ₹']} rows={[['Kottur temple','312','19','1 sponsor','4,500'],['Ashta Dravya Homam','148','3','—','225'],['Sponsor a temple','41','—','—','—']]}/></div></AShell>)
}
export function ASubmit() {
  const [s,setS]=useState(0)
  const steps=['Basics','Location','About & story','Guidelines & nearby','Photos','Contact','Review']
  return (<AShell><H t="Add a temple" s="Every section below is required before staff can verify"/><Steps items={steps} at={s}/>
    <div className="card space-y-4 p-5">
      {s===0&&<><div className="grid gap-4 md:grid-cols-2"><Field label="Temple name (English)"><Input placeholder="Sree … Temple"/></Field><Field label="Temple name (Malayalam)"><Input placeholder="ശ്രീ … ക്ഷേത്രം"/></Field><Field label="Main deity"><Select options={['Vishnu','Shiva','Bhagavathi','Ganapathi','Subrahmanya','Sastha','Other']}/></Field><Field label="Other deities (upadevathas)"><Input placeholder="Ganapathi, Naga, Yakshi"/></Field><Field label="Managed by"><Select options={['Committee','Devaswom board','Family / Illam','Trust']}/></Field><Field label="Timings"><Input placeholder="5:30–9:30 AM, 5:30–7:30 PM"/></Field></div></>}
      {s===1&&<><div className="grid gap-4 md:grid-cols-2"><Field label="District"><Select options={['Kozhikode','Malappuram','Thrissur']}/></Field><Field label="Panchayat / town"><Input/></Field><Field label="Address" className="md:col-span-2"><textarea className="input" rows={2}/></Field></div><button className="btn-g">Use my current location</button><div className="photo aspect-[16/6] rounded-xl"/></>}
      {s===2&&<><Field label="About the temple" hint="2–4 sentences. What is it known for?"><textarea className="input" rows={3}/></Field><Field label="Story (aithihyam)"><textarea className="input" rows={3}/></Field><Field label="History"><textarea className="input" rows={3}/></Field><Field label="Speciality"><textarea className="input" rows={2}/></Field></>}
      {s===3&&<><Field label="Guidelines for devotees" hint="Dress code, photography, prasadam timing"><textarea className="input" rows={3}/></Field><Field label="Remarks"><textarea className="input" rows={2}/></Field><Field label="Nearby places to visit" hint="One per line with distance"><textarea className="input" rows={3}/></Field></>}
      {s===4&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[1,2,3,4].map(i=><button key={i} className="grid aspect-square place-items-center rounded-xl border-2 border-dashed border-brown-200 text-sm text-brown-500">+ photo</button>)}</div><p className="text-xs text-brown-500">At least one photo of the sreekovil or entrance. No photos of the deity's face inside the sanctum.</p></>}
      {s===5&&<><div className="grid gap-4 md:grid-cols-2"><Field label="Secretary / contact name"><Input/></Field><Field label="WhatsApp number"><Input placeholder="+91"/></Field><Field label="Email (for chart)"><Input/></Field><Field label="Bank account & IFSC (optional now)" hint="Needed before bookings; payouts can be manual NEFT if there's no gateway"><Input/></Field></div><Toggle label="Committee agreed to online booking (I'll upload the letter at KYC)"/></>}
      {s===6&&<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Submitting sends this to staff for verification. You earn ₹100 when approved and ₹200 when the temple completes KYC. The committee can later claim the page and take ownership.</div>}
      <div className="flex gap-2">{s>0&&<button onClick={()=>setS(s-1)} className="btn-g">Back</button>}{s<6?<button onClick={()=>setS(s+1)} className="btn-p flex-1">Next</button>:<Link to="/agent/submissions" className="btn-p flex-1">Submit for verification</Link>}</div></div></AShell>)
}
export function ASubmissions() {
  return (<AShell><H t="My submissions"/><div className="card p-4"><Table head={['Temple','Submitted','Status','Owner','Earned']} rows={[['Vengamala Bhagavathi Temple','2 Sept',<Pill tone="ok">Verified · bookings on</Pill>,'Agent (you) → claim pending by secretary','₹300'],['Kottur Sree Mahavishnu Temple','4 Jul',<Pill tone="ok">Verified · Pro</Pill>,'Transferred to committee 2 Aug','₹4,800'],['Sree Neelakeshi Mudippura Temple','9 Sept',<Pill tone="warn">Pending review</Pill>,'—','—'],['Vithura Sree Mahadeva Temple','6 Sept',<Pill tone="err">Needs changes</Pill>,'Staff: history & guidelines missing','—']]}/></div></AShell>)
}

/* ================= DEALER ================= */
const dealerItems=[{group:'Dealer',links:[['/dealer','Territory',Map],['/dealer/agents','Agents',Users],['/agent','My wallet',Wallet]]}]
const DShell = ({children}) => <DashShell role="Dealer" user="Rahul · Kozhikode North" items={dealerItems}>{children}</DashShell>
export function DDash() {
  return (<DShell><H t="Kozhikode North" s="Pincodes 673001–673029 · 14 agents" right={<Link to="/agent" className="btn-p"><Wallet size={16}/>My wallet · ₹18,320</Link>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat v="86" l="temples live"/><Stat v="21" l="paying / sponsored"/><Stat v="₹2,64,000" l="territory revenue YTD"/><Stat v="₹13,200" l="override this month"/></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_320px]"><div className="card p-5"><h3 className="font-semibold">Agents</h3><Table head={['Agent','Listings','Verified','Plans + sponsors','This month ₹']} rows={[['Jinsha (JIN-4471)','23','19','4','6,375'],['Arun (ARU-2210)','17','14','2','2,100'],['Sangeetha (SAN-0932)','11','9','3','4,950'],['Faisal (FAI-1187)','4','2','0','200']]}/><Link to="/dealer/agents" className="mt-2 block text-sm text-saffron-600">All 14 agents</Link></div>
      <aside className="space-y-4"><div className="card p-5 text-sm"><b>Expiring in 30 days</b><div className="mt-1 text-brown-600">Thrikapaleshwaram — Basic (28 Sept)<br/>Prasad Nambeesan — Service Pro (4 Oct)</div><div className="mt-1 text-xs text-brown-500">Renewal earns 5% agent + 2% dealer</div></div><div className="card p-5 text-sm"><b>Pending agent requests</b><div className="text-brown-600">2 new agents want to join · <Link to="/dealer/agents" className="text-saffron-600">Review</Link></div></div></aside></div></DShell>)
}
export function DAgents() {
  return (<DShell><H t="Agents · Kozhikode North"/><div className="card p-4"><Table head={['Agent','Code','Joined','Listings','Earned YTD','Status','']} rows={[['Jinsha','JIN-4471','Mar 2026','23','₹28,340',<Pill tone="ok">Active</Pill>,'Deactivate'],['Arun','ARU-2210','Apr 2026','17','₹12,100',<Pill tone="ok">Active</Pill>,'Deactivate'],['Sangeetha','SAN-0932','May 2026','11','₹15,900',<Pill tone="ok">Active</Pill>,'Deactivate'],['Meera','—','Requested 10 Sept','—','—',<Pill tone="warn">Pending</Pill>,<span><b className="text-emerald-700">Approve</b> · Reject</span>],['Sudheesh','—','Requested 11 Sept','—','—',<Pill tone="warn">Pending</Pill>,<span><b className="text-emerald-700">Approve</b> · Reject</span>]]}/></div></DShell>)
}

/* ================= STAFF / SUPER ADMIN ================= */
// Staff is split into three sub-roles, chosen at login (?role= on every /staff* URL):
//  · moderator  — reviews listings, temples, service providers, agents, bookings & daily charts
//  · accountant — financial reports, vendor/agent/dealer payouts, manual NEFT sheet
//  · admin      — Portal admin: settings, approvals for staff/accountant/dealer, KYC & fee config, maintenance mode
const staffNav = role => {
  const q = `?role=${role}`
  if (role==='moderator') return [{group:'Moderation',links:[['/staff'+q,'Queues',Inbox],['/staff/listing'+q,'Listing review',ListChecks],['/staff/kyc'+q,'KYC',ShieldCheck],['/staff/charts'+q,'Daily charts',CalendarCheck],['/staff/special'+q,'Special poojas',Sparkles],['/staff/ownership'+q,'Claims & transfers',ArrowRightLeft]]}]
  if (role==='accountant') return [{group:'Finance',links:[['/staff'+q,'Queues',Inbox],['/staff/payouts'+q,'Payouts',Landmark],['/staff/withdrawals'+q,'Wallet withdrawals',HandCoins],['/staff/sponsors'+q,'Sponsors & plans',Banknote],['/staff/analytics'+q,'Analytics',BarChart3]]}]
  return [{group:'Work queues',links:[['/staff'+q,'Queues',Inbox],['/staff/analytics'+q,'Analytics',BarChart3],['/staff/payouts'+q,'Payouts',Landmark],['/staff/listing'+q,'Listing review',ListChecks],['/staff/kyc'+q,'KYC',ShieldCheck],['/staff/charts'+q,'Charts',CalendarCheck],['/staff/special'+q,'Special poojas',Sparkles],['/staff/withdrawals'+q,'Wallet withdrawals',HandCoins],['/staff/ownership'+q,'Claims & transfers',ArrowRightLeft],['/staff/sponsors'+q,'Sponsors & plans',Banknote],['/staff/backup'+q,'Backup & restore',Database]]},{group:'Portal admin',links:[['/staff/config'+q,'Configuration',Settings2],['/staff/tables'+q,'Advanced → tables',Table2]]}]
}
const staffRoleLabel = {moderator:'Staff · Moderator', accountant:'Staff · Accountant', admin:'Staff · Portal admin'}
const SShell = ({children}) => { const [sp]=useSearchParams(); const role = staffRoleLabel[sp.get('role')] ? sp.get('role') : 'admin'
  return <DashShell role={staffRoleLabel[role]} user="Anand · Admin" items={staffNav(role)} badge="24">{children}</DashShell> }
const Q = ({c,t,s,h,hot}) => <Link to={h} className="card flex items-center gap-3 p-4 transition hover:shadow-soft"><span className={`grid h-11 w-11 place-items-center rounded-xl text-lg font-bold ${hot?'bg-saffron-50 text-saffron-600':'bg-brown-50 text-brown-800'}`}>{c}</span><span className="flex-1"><b className="block text-sm">{t}</b><span className="text-xs text-brown-500">{s}</span></span><span className="btn-g !py-1.5 text-xs">Open</span></Link>

export function SQueues() {
  return (<SShell><H t="Work queues" s="Fri 11 Sept 2026, 11:20 AM" right={<Link to="/staff/analytics" className="btn-g"><BarChart3 size={16}/>Analytics</Link>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat v="1,240" l="verified temples" delta="+38 this week"/><Stat v="168" l="bookings today"/><Stat v="₹46,300" l="payable to temples"/><Stat v="₹1,12,400" l="revenue this month" delta="+22% vs Aug"/></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2"><Q c={12} t="Pending listings" s="oldest 4 days · 3 from agents" h="/staff/listing" hot/><Q c={5} t="KYC to review" s="2 with 80G certificates" h="/staff/kyc" hot/><Q c={3} t="Charts unconfirmed" s="past cutoff · auto-confirm at 11 PM" h="/staff/charts" hot/><Q c={4} t="Claims & ownership transfers" s="2 claims · 2 transfers awaiting OTP" h="/staff/ownership" hot/><Q c={7} t="Special poojas to fulfil" s="14 Sept Ganapathi Homam · 22 seats" h="/staff/special"/><Q c={1} t="Payout batch ready" s="₹46,300 · 38 temples · 9 manual NEFT" h="/staff/payouts"/><Q c={4} t="Wallet withdrawals" s="₹19,840 · agents & dealers" h="/staff/withdrawals"/><Q c={2} t="Offline payments to confirm" s="1 sponsorship, 1 plan" h="/staff/sponsors"/><Q c={1} t="Restore request" s="Vengamala — pooja list as of 1 Aug" h="/staff/backup"/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Today</h3><Table head={['Metric','Value']} rows={[['Bookings / donations / special / service','142 / 9 / 12 / 5'],['Gateway split','Razorpay 118 · PayU 9 · Stripe 4 · Omniware (own) 37'],['Failed payments','6 (retry links sent)'],['Chatbot conversations','214 · 31 handed to WhatsApp support'],['Backup','Last full backup 02:10 today · OK']]}/></div></SShell>)
}

export function SAnalytics() {
  const traffic=analytics.traffic.map(([m,v,u])=>({m,visits:v,users:u})); const bk=analytics.bookings.map(([d,n])=>({d,n}))
  const C=['#E8722A','#25D366','#4A3527','#C99A3C']
  return (<SShell><H t="Analytics" s="Google Analytics 4 · Play/App Store · WhatsApp (Libromi) · TempleAddress DB" right={<Select options={['Last 30 days','Last 90 days','This year']}/>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat v="44.2k" l="site sessions (GA4)" delta="+14% MoM"/><Stat v="13.8k" l="active users"/><Stat v="6,120" l="app installs (Android 5,340 · iOS 780)" delta="+412 this month"/><Stat v="2,930" l="new WhatsApp users" delta="+18% MoM"/></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3">
      <div className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><Globe size={16}/><h3 className="font-semibold">Traffic — sessions vs users (thousands)</h3></div><div className="mt-3 h-56"><ResponsiveContainer><LineChart data={traffic}><CartesianGrid stroke="#F1E7D8"/><XAxis dataKey="m" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Line isAnimationActive={false} type="monotone" dataKey="visits" stroke="#E8722A" strokeWidth={2.5} dot={false}/><Line isAnimationActive={false} type="monotone" dataKey="users" stroke="#4A3527" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></div>
      <div className="card p-5"><h3 className="font-semibold">Booking channel</h3><div className="h-56"><ResponsiveContainer><PieChart><Pie data={analytics.channels} dataKey="value" nameKey="name" innerRadius={50} outerRadius={80} isAnimationActive={false}>{analytics.channels.map((_,i)=><Cell key={i} fill={C[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="flex flex-wrap gap-2 text-xs">{analytics.channels.map((c,i)=><span key={c.name} className="flex items-center gap-1"><span className="h-2.5 w-2.5 rounded-full" style={{background:C[i]}}/>{c.name} {c.value}%</span>)}</div></div>
      <div className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><TrendingUp size={16}/><h3 className="font-semibold">Bookings by weekday</h3></div><div className="mt-3 h-48"><ResponsiveContainer><BarChart data={bk}><CartesianGrid stroke="#F1E7D8" vertical={false}/><XAxis dataKey="d" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Bar isAnimationActive={false} dataKey="n" fill="#E8722A" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div>
      <div className="card p-5"><h3 className="font-semibold">Top pages (GA4)</h3><Table head={['Page','Views']} rows={[['/t/kottur-sree-mahavishnu-temple','8,420'],['/special','6,130'],['/t/thrikapaleshwaram-temple','4,910'],['/festival','3,220'],['/sponsor','1,040']]}/></div>
    </div>
    <div className="mt-5 grid gap-5 md:grid-cols-3"><div className="card p-5"><div className="flex items-center gap-2"><Smartphone size={16}/><b>App</b></div><Table head={['Metric','Value']} rows={[['Installs (30d)','412'],['DAU / MAU','1,140 / 4,320'],['Crash-free','99.4%'],['Store rating','4.6 ★ (318)']]}/></div><div className="card p-5"><div className="flex items-center gap-2"><MessageCircle size={16}/><b>WhatsApp (Libromi)</b></div><Table head={['Metric','Value']} rows={[['New users (30d)','2,930'],['Bookings via bot','1,204'],['Chart confirmations','98% within 1 h'],['Template delivery','99.1%']]}/></div><div className="card p-5"><div className="flex items-center gap-2"><Sparkles size={16}/><b>Assistant</b></div><Table head={['Metric','Value']} rows={[['Conversations (30d)','6,410'],['Answered from TA data','84%'],['Handed to support','9%'],['Led to a booking','21%']]}/></div></div></SShell>)
}

export function SListing() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="Sree Neelakeshi Mudippura Temple" s="Submitted by Jinsha (JIN-4471) · 9 Sept" right={<Pill tone="warn">Pending</Pill>}/>
    <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5">
      <div className="card p-5"><h3 className="font-semibold">Completeness</h3><div className="mt-2 flex flex-wrap gap-2">{[['Basics',1],['Location',1],['About',1],['Story',1],['History',0],['Speciality',1],['Guidelines',0],['Remarks',1],['Nearby',1],['Deities',1],['Photos (3)',1],['Contact',1]].map(([n,ok])=><Pill key={n} tone={ok?'ok':'err'}>{ok?<Check size={12}/>:'✕'} {n}</Pill>)}</div><p className="mt-2 text-xs text-brown-500">History and Guidelines are empty — ask the agent, or verify with a note.</p></div>
      <div className="card p-5"><h3 className="font-semibold">Submitted details</h3><Table head={['Field','Value','']} rows={[['Name (EN)','Sree Neelakeshi Mudippura Temple','Edit'],['Name (ML)',<span className="ml">ശ്രീ നീലകേശി മുടിപ്പുര ക്ഷേത്രം</span>,'Edit'],['Deity','Bhagavathi (Neelakeshi) · Ganapathi, Naga','Edit'],['District','Thiruvananthapuram','Edit'],['Address','Mudippura, Vellanad PO – 695543','Edit'],['About','Village Bhagavathi temple known for Mudippura festival in Meenam…','Edit'],['Nearby','Neyyar dam (14 km), Agasthyakoodam base (22 km)','Edit'],['Contact','+91 98… 3312 (Secretary)','Edit']]}/></div>
      <div className="card p-5"><h3 className="font-semibold">Checks</h3><div className="mt-2 space-y-2"><Toggle label="Not a duplicate (nearest: Vellanad Devi Temple, 3.1 km)" defaultChecked/><br/><Toggle label="Photos show the temple exterior" defaultChecked/><br/><Toggle label="Phone verified by call"/></div></div></div>
      <aside className="card space-y-3 p-5"><button onClick={()=>toast('Verified — page live, bookings off until KYC')} className="btn-p w-full">Verify & publish</button><button className="btn-s w-full">Ask agent for changes</button><button className="btn w-full bg-red-50 text-red-700">Reject</button><textarea className="input" rows={3} placeholder="Note to agent"/><p className="text-xs text-brown-500">On verify: agent gets ₹100 (pending 15 days), dealer ₹20. The secretary receives a WhatsApp invite to claim the page and set poojas & KYC.</p></aside></div></SShell>)
}
export function SKyc() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="KYC review"/><div className="card p-4"><Table head={['Temple','Submitted','Documents','Payment mode','80G','Action']} rows={[['Vengamala Bhagavathi Temple','9 Sept','Committee letter · PAN · Bank proof','Bank only → manual NEFT','No',<b className="text-saffron-600">Review</b>],['Kunnathumadom Sree Krishna Temple','8 Sept','Committee letter · PAN · Bank proof · 80G cert','Razorpay via TA',<Pill tone="gold">Yes</Pill>,<b className="text-saffron-600">Review</b>],['Vizhinjam Sree Bhagavathy Temple','7 Sept','Trust deed · PAN · Omniware MID','Omniware (own)','No',<b className="text-saffron-600">Review</b>],['Vithura Sree Mahadeva Temple','6 Sept','Committee letter only','—','—','Waiting for bank proof']]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Kunnathumadom Sree Krishna Temple</h3><div className="mt-3 grid grid-cols-2 gap-3"><div className="photo aspect-[4/3] rounded-xl p-3 text-xs text-white">Committee resolution.pdf</div><div className="photo aspect-[4/3] rounded-xl p-3 text-xs text-white">80G certificate.pdf</div></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Trust PAN"><Input defaultValue="AAATK9981C"/></Field><Field label="80G reg no."><Input defaultValue="AAATK9981CF20231"/></Field><Field label="Bank"><Input defaultValue="SBI ····7720 · SBIN0070231"/></Field><Field label="Penny-drop name match"><Input defaultValue="KUNNATHUMADOM DEVASWOM — 96%"/></Field></div>
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>toast('KYC approved — bookings on, 80G receipts enabled')} className="btn-p">Approve · enable bookings & 80G</button><button className="btn-s">Approve without 80G</button><button className="btn bg-red-50 text-red-700">Reject</button></div></div></SShell>)
}
export function SCharts() {
  return (<SShell><H t="Charts"/><div className="mb-4 rounded-xl bg-saffron-50 p-3 text-sm text-saffron-800">3 temples haven't confirmed tonight's chart. Auto-confirm runs at 11 PM; devotees are already booked.</div>
    <div className="card p-4"><Table head={['Temple','Date','#','₹','Sent','Status','Action']} rows={[['Kottur Sree Mahavishnu','13 Sept','14','3,420','WhatsApp ✓ Email ✓',<Pill tone="warn">Prepared</Pill>,'Force confirm · Resend'],['Edakkayil Maha Ganapathi','13 Sept','6','740','WhatsApp ✓ Email ✗ bounced',<Pill tone="warn">Prepared</Pill>,'Force confirm · Fix email'],['Vengamala Bhagavathi','13 Sept','2','60','WhatsApp ✓',<Pill tone="warn">Prepared</Pill>,'Force confirm'],['Bilathikulam Sree Shiva','13 Sept','8','1,940','WhatsApp ✓',<Pill tone="ok">Confirmed</Pill>,'View'],['Thrikapaleshwaram','13 Sept','11','2,760','WhatsApp ✓ Email ✓',<Pill tone="ok">Confirmed</Pill>,'View']]}/></div>
    <div className="mt-3 flex gap-2"><button className="btn-s">Prepare now (all)</button><button className="btn-g"><Download size={16}/>Today's PDFs</button></div></SShell>)
}
export function SSpecial() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="Special pooja fulfilment"/><div className="card p-4"><Table head={['Pooja','Date','Temple','Seats','Collected ₹','Temple cost ₹','Margin ₹','Status','Action']} rows={[['Ashta Dravya Maha Ganapathi Homam','14 Sept','Kottur Mahavishnu','22 / 40','33,000','15,000','18,000',<Pill tone="warn">Confirm with temple</Pill>,'Send sankalpam list'],['Pithru Tharpanam','26 Sept','Thrikapaleshwaram','31 / 60','65,100','30,000','35,100',<Pill>Open</Pill>,'—'],['Bhagavathi Seva','12 Sept','Vengamala','9 / 40','6,750','3,500','3,250',<Pill tone="info">Performed</Pill>,<b className="text-saffron-600">Upload proof</b>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Bhagavathi Seva · 12 Sept · upload proof</h3><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{['+ photo','+ photo','+ video','prasadam dispatch'].map(x=><button key={x} className="grid aspect-square place-items-center rounded-xl border-2 border-dashed border-brown-200 text-sm text-brown-500">{x}</button>)}</div><button onClick={()=>toast('Proof sent to 9 devotees on WhatsApp')} className="btn-p mt-4">Send proof to devotees & mark done</button><span className="ml-2 text-xs text-brown-500">Creates vendor payable ₹3,500 to Vengamala.</span></div></SShell>)
}

/* -------- PAYOUTS: manual NEFT sheet flow -------- */
export function SPayouts() {
  const [step,setStep]=useState(1); const [toast,el]=useToast(); const [tab,setTab]=useState(0)
  const rows=[['PO-2637-001','Kottur Sree Mahavishnu','Razorpay via TA','7','12,650','FDRL ····4412 · FDRL0001234'],['PO-2637-002','Thrikapaleshwaram','Razorpay via TA','7','9,120','SBIN ····0192 · SBIN0070231'],['PO-2637-003','Edakkayil Maha Ganapathi','PayU via TA','6','4,780','CNRB ····5531 · CNRB0001120'],['PO-2637-004','Vengamala Bhagavathi','Bank only (manual)','5','2,460','FDRL ····2201 · FDRL0002201'],['PO-2637-005','Vengamala Bhagavathi (special pooja cost)','Bank only (manual)','1','3,500','FDRL ····2201 · FDRL0002201'],['PO-2637-006','Kunnathumadom Sree Krishna','Bank only (manual)','4','1,890','SBIN ····7720 · SBIN0070231'],['…','32 more','','','11,900','']]
  return (<SShell>{el}<H t="Payouts" s="Batch #2026-37 · charts completed 1–7 Sept · 38 temples · ₹46,300" right={<Pill tone="info">Manual NEFT until RazorpayX is added</Pill>}/>
    <Tabs tabs={['This batch','History','Settings']} at={tab} set={setTab}/>
    {tab===0 && <><Steps items={['Batch created','Export Excel','Pay in internet banking','Import UTRs','Marked paid']} at={step}/>
      <div className="mb-4 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900"><b>How this works.</b> Every completed chart creates a payable. On Monday the accountant exports this sheet, uploads it to the bank's bulk-NEFT portal (or pays one by one), then fills the <b>UTR / journal no.</b> column in the same sheet and imports it back. Rows with a UTR are marked <b>Paid</b> and the temple gets a WhatsApp. Custom-gateway temples (Omniware) never appear here.</div>
      <div className="card p-4"><Table head={['Payout ref','Temple','Collected via','Charts','Amount ₹','Beneficiary (A/c · IFSC)']} rows={rows}/></div>
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>{setStep(2);toast('NEFT sheet downloaded: payouts-2026-37.xlsx')}} className="btn-p"><Download size={16}/>Export NEFT Excel</button><button onClick={()=>setStep(3)} className="btn-s"><Upload size={16}/>Import completed sheet</button><button className="btn-g">Mark one as paid</button></div>
      {step>=3 && <div className="card mt-5 p-5"><h3 className="font-semibold">Import preview · payouts-2026-37.xlsx</h3><p className="text-xs text-brown-500">Columns read: payout_ref, amount, utr_or_journal_no, paid_on, remarks</p><div className="mt-3"><Table head={['Payout ref','Temple','₹','UTR / journal','Paid on','Result']} rows={[['PO-2637-001','Kottur Sree Mahavishnu','12,650','FDRLN26251000431','15 Sept',<Pill tone="ok">Will mark paid</Pill>],['PO-2637-002','Thrikapaleshwaram','9,120','—','—',<Pill tone="err">Failed: IFSC invalid</Pill>],['PO-2637-004','Vengamala Bhagavathi','2,460','FDRLN26251000432','15 Sept',<Pill tone="ok">Will mark paid</Pill>],['PO-2637-005','Vengamala Bhagavathi','3,500','FDRLN26251000432','15 Sept',<Pill tone="ok">Will mark paid (same UTR)</Pill>],['PO-2637-006','Kunnathumadom','1,890','JRN-0921-44','15 Sept',<Pill tone="ok">Will mark paid (journal)</Pill>]]}/></div><button onClick={()=>{setStep(4);toast('36 payouts marked paid · temples notified on WhatsApp')}} className="btn-p mt-3"><Check size={16}/>Apply · mark paid</button></div>}</>}
    {tab===1 && <div className="card p-4"><Table head={['Batch','Period','Temples','₹','Exported','Imported','Paid / failed']} rows={[['#2026-36','25–31 Aug','36','44,120','1 Sept','1 Sept','36 / 0'],['#2026-35','18–24 Aug','34','41,860','25 Aug','25 Aug','33 / 1'],['#2026-34','11–17 Aug','31','38,200','18 Aug','19 Aug','31 / 0']]}/></div>}
    {tab===2 && <div className="card grid gap-4 p-5 md:grid-cols-2"><Field label="Payout cycle"><Select options={['Weekly (Monday)','On ₹5,000 threshold','Manual']}/></Field><Field label="Minimum payout ₹"><Input defaultValue="500"/></Field><Field label="Sheet format"><Select options={['Federal Bank bulk NEFT','SBI CINB bulk','Generic (payout_ref, name, acct, ifsc, amount, utr)']}/></Field><Field label="Payout product" hint="When connected, batches are paid automatically; the Excel flow stays as fallback"><Select options={['Manual NEFT (current)','RazorpayX (not connected)','Cashfree Payouts (not connected)']}/></Field></div>}
  </SShell>)
}
export function SWithdrawals() {
  return (<SShell><H t="Wallet withdrawals" s="Same export / import mechanism as temple payouts · wallet debited only when marked paid"/><div className="card p-4"><Table head={['Requested','Who','Role','₹','TDS','Net ₹','Pay to','Status','']} rows={[['11 Sept','Jinsha (JIN-4471)','Agent','6,840','342','6,498','UPI jinsha@okaxis',<Pill tone="warn">Requested</Pill>,<b className="text-emerald-700">Approve</b>],['10 Sept','Rahul','Dealer','10,000','500','9,500','FDRL ····9902',<Pill tone="warn">Requested</Pill>,<b className="text-emerald-700">Approve</b>],['9 Sept','Sangeetha (SAN-0932)','Agent','2,000','100','1,900','UPI',<Pill tone="info">In batch</Pill>,'—'],['8 Sept','Arun (ARU-2210)','Agent','1,000','50','950','UPI',<Pill tone="info">In batch</Pill>,'—']]}/></div><div className="mt-3 flex gap-2"><button className="btn-p"><Download size={16}/>Export withdrawal sheet</button><button className="btn-s"><Upload size={16}/>Import UTRs</button></div></SShell>)
}
export function SOwnership() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="Claims & ownership transfers"/>
    <div className="card p-5"><h3 className="font-semibold">Claims</h3><Table head={['Temple','Claimant','Role','Current owner','Docs','Phone check','Action']} rows={[['Vengamala Bhagavathi Temple','Suresh P','Secretary','Agent Jinsha','Resolution ✓ · PAN ✓ · ID ✓',<Pill tone="ok">Matches listed no.</Pill>,<button onClick={()=>toast('Claim approved — ownership moved to Suresh P')} className="btn-p !py-1.5 text-xs">Approve</button>],['Edakkayil Maha Ganapathi','Anitha R','Treasurer','Unclaimed','Resolution ✓ · PAN ✗',<Pill tone="warn">Different number</Pill>,<button className="btn-g !py-1.5 text-xs">Call & verify</button>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Transfers awaiting acceptance</h3><Table head={['Temple','From','To','Reason','Requested','Status']} rows={[['Thrikapaleshwaram Temple','Gopan (Secretary)','Ravi (new Secretary)','Committee election','10 Sept',<Pill tone="warn">OTP not yet accepted</Pill>],['Bilathikulam Sree Shiva','Committee','Devaswom board','Devaswom takeover','9 Sept',<Pill tone="warn">Docs under review</Pill>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Audit log</h3><Table head={['Date','Listing','Event','By']} rows={[['2 Aug','Kottur Sree Mahavishnu','Owner: agent Jinsha → Nishanth K (claim)','Staff Anand'],['14 Jul','Prasad Nambeesan (service)','Owner set at signup','System'],['9 Jul','Kottur Sree Mahavishnu','Verified','Staff Anand']]}/></div></SShell>)
}
export function SSponsors() {
  return (<SShell><H t="Sponsors & plans"/><div className="card p-5"><h3 className="font-semibold">Offline payments to confirm</h3><Table head={['Date','Payer','For','₹','Method','Ref','']} rows={[['10 Sept','Malabar Gold Traders','Sponsor Patron → Edakkayil Maha Ganapathi','35,400','Bank transfer','UTR FDRLN262…',<b className="text-emerald-700">Confirm & activate</b>],['9 Sept','Thrikapaleshwaram Committee','Temple Basic renewal','6,000','Cheque','#004112',<b className="text-emerald-700">Confirm & activate</b>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Active subscriptions</h3><Table head={['Subscriber','Plan','Sponsored by','Start','Expiry','GST inv.','Status']} rows={[['Kottur Sree Mahavishnu','Pro','Resurge India Foundation (Patron)','1 Aug 2026','31 Jul 2027','INV-0412',<Pill tone="ok">Active</Pill>],['Thrikapaleshwaram','Basic','—','28 Sept 2025','28 Sept 2026','INV-0298',<Pill tone="warn">Expires in 17 days</Pill>],['Prasad Nambeesan','Service Pro','—','4 Oct 2025','4 Oct 2026','INV-0301',<Pill tone="warn">Expires in 23 days</Pill>],['Bilathikulam Sree Shiva','Basic','—','1 Jun 2026','31 May 2027','INV-0388',<Pill tone="ok">Active</Pill>]]}/></div></SShell>)
}
export function SBackup() {
  return (<SShell><H t="Backup & restore"/><div className="grid grid-cols-3 gap-3"><Stat v="02:10 today" l="last full backup · OK"/><Stat v="30 days" l="retention · off-site"/><Stat v="12 Jun" l="last restore drill · passed"/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Restore requests</h3><Table head={['Temple','Requested by','What','Point in time','Status','']} rows={[['Vengamala Bhagavathi','Secretary (+91 98…) · verified by call','Pooja list & prices','1 Aug 2026',<Pill tone="warn">Verify identity</Pill>,<span><b className="text-emerald-700">Run restore</b> · Reject</span>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Export jobs</h3><Table head={['Temple','Type','Started','Size','Status']} rows={[['Kottur Sree Mahavishnu','Monthly auto','1 Sept 02:30','18 MB',<Pill tone="ok">Delivered</Pill>],['Edakkayil Maha Ganapathi','On request','11 Sept 10:02','9 MB',<Pill tone="info">Running</Pill>]]}/></div></SShell>)
}
export function SConfig() {
  const [tab,setTab]=useState(0); const [toast,el]=useToast(); const [maint,setMaint]=useState(false)
  const feeRow=(t,m,v,r)=>[t,<Select options={['Off','Percent','Fixed','Percent + fixed']} defaultValue={m}/>,<Input defaultValue={v} className="input !w-20"/>,<Select options={['Devotee','Temple']}/>,<Select options={['Yes','No']} defaultValue={r}/>,'18%']
  return (<SShell>{el}<H t="Configuration" s="Portal admin only — approvals, KYC & fee policy, and platform-wide switches"/><Tabs tabs={['Convenience fee','Payment gateways','Plans','Agent rates','Chatbot','General']} at={tab} set={setTab}/>
    {tab===0 && <div className="card p-5"><h3 className="font-semibold">Platform defaults (used when a listing says “inherit”)</h3><div className="mt-3"><Table head={['Transaction type','Mode','Value','Who pays','Refundable','GST on fee']} rows={[feeRow('Vazhipadu','Off','0','Yes'),feeRow('Donation','Off','0','Yes'),feeRow('Special pooja','Percent','2','No'),feeRow('Service','Off','0','Yes')]}/></div><div className="mt-3 rounded-xl bg-saffron-50 p-3 text-sm text-saffron-800">Resolution: <b>listing override → platform default → 0</b>. 3 listings currently override.</div><button onClick={()=>toast('Defaults saved')} className="btn-p mt-3">Save defaults</button></div>}
    {tab===1 && <div className="card p-5"><h3 className="font-semibold">Platform gateway accounts</h3><p className="text-sm text-brown-500">Temples pick which of these to offer (or use their own).</p><div className="mt-3"><Table head={['Gateway','Mode','Customer fee bearer','Webhook','Status','']} rows={[['Razorpay','Platform account · default','Enabled','/api/payments/webhooks/razorpay/ ✓',<Pill tone="ok">Live</Pill>,'Keys'],['PayU','Platform account','Enabled','/api/payments/webhooks/payu/ ✓',<Pill tone="ok">Live</Pill>,'Keys'],['Stripe','Platform account · international','Absorbed · shown as line','/api/payments/webhooks/stripe/ ✓',<Pill tone="ok">Live</Pill>,'Keys'],['Omniware (Federal Bank)','Temple\'s own account (custom)','Per temple','/api/payments/webhooks/omniware/{listing} ✓',<Pill tone="ok">Live</Pill>,'—'],['RazorpayX (payouts)','Not connected','—','—',<Pill>Planned</Pill>,'Connect']]}/></div><div className="mt-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">Custom-gateway listings are excluded from payables and payouts automatically. Bank-only listings go to the manual NEFT sheet.</div></div>}
    {tab===2 && <div className="card p-5"><Table head={['Plan','₹/yr','White-label','Custom domain','WhatsApp chart','Admin phones','Self backup','Ads off']} rows={[['Free','0','—','—','—','1','On request','—'],['Temple Basic','6,000','—','—','✓','1','✓','✓'],['Temple Pro','15,000','✓','✓','✓','3','✓ monthly','✓'],['Service Pro','3,000','—','—','✓','1','✓','✓'],['Sponsor Supporter / Patron / Benefactor','15k / 30k / 50k','grants Pro to temple','','','','','']]}/><button className="btn-s mt-3">Edit plans</button></div>}
    {tab===3 && <div className="card p-5"><Table head={['Event','Agent','Dealer','Hold']} rows={[['Listing approved','₹100','₹20','15 days'],['KYC + bookings on','₹200','₹40','15 days'],['Plan paid (first year)','15%','5%','15 days'],['Sponsorship (ex-GST)','15%','5%','15 days'],['Renewal','5%','2%','15 days'],['Special pooja via link','5%','—','after pooja + 15 days'],['Fee revenue from agent\'s listing','10% (12 mo)','3%','monthly']]}/><div className="mt-3 grid gap-4 md:grid-cols-2"><Field label="Minimum withdrawal ₹"><Input defaultValue="500"/></Field><Field label="Withdrawal cycle"><Select options={['Monthly (last working day)','Weekly']}/></Field></div><button className="btn-p mt-3">Save</button></div>}
    {tab===4 && <div className="card grid gap-4 p-5 md:grid-cols-2"><Field label="Model provider" hint="Swappable; the bot only reads TempleAddress data"><Select options={['OpenAI-compatible','Gemini','Local (Ollama)']}/></Field><Field label="Knowledge sources"><Select options={['Listings + poojas + festivals + FAQs (default)','Listings only']}/></Field><Field label="Escalate to WhatsApp support when"><Select options={['Confidence < 0.6 or booking/refund intent','Never']}/></Field><Field label="Languages"><Select options={['English + Malayalam','English']}/></Field><Field label="System prompt" className="md:col-span-2"><textarea className="input" rows={3} defaultValue="You are the TempleAddress assistant. Answer only from the provided temple data. Never invent timings or prices. Offer to start a booking when relevant."/></Field><button className="btn-p">Save</button></div>}
    {tab===5 && <div className="space-y-5">
      <div className="card grid gap-4 p-5 md:grid-cols-2"><Field label="Default chart cutoff"><Select options={['7:00 PM','8:00 PM','9:00 PM']} defaultValue="8:00 PM"/></Field><Field label="Auto-confirm unconfirmed charts at"><Select options={['10:00 PM','11:00 PM','Never']} defaultValue="11:00 PM"/></Field><Field label="Booking window (days ahead)"><Input defaultValue="30"/></Field><Field label="GST % on TA services"><Input defaultValue="18"/></Field><Field label="Google Analytics 4 property"><Input defaultValue="G-TA2026KL"/></Field><Field label="WhatsApp provider"><Input defaultValue="Libromi · +91 9495 041196"/></Field><Field label="Backup retention (days)"><Input defaultValue="30"/></Field><Field label="Platform convenience fee — global cap %" hint="Ceiling a listing's override cannot exceed"><Input defaultValue="5"/></Field><button onClick={()=>toast('General settings saved')} className="btn-p self-end">Save</button></div>
      <div className="card p-5"><h3 className="font-semibold">Staff, accountant & dealer approvals</h3><p className="text-sm text-brown-500">New staff, accountant and dealer accounts stay disabled until a Portal admin approves them here.</p>
        <div className="mt-3"><Table head={['Name','Requested role','Requested','Action']} rows={[['Deepa Menon','Accountant','10 Sept',<span><b className="text-emerald-700">Approve</b> · Reject</span>],['Vishnu R','Moderator','9 Sept',<span><b className="text-emerald-700">Approve</b> · Reject</span>],['Kozhikode East — new dealer','Dealer','8 Sept',<span><b className="text-emerald-700">Approve</b> · Reject</span>]]}/></div></div>
      <div className="card p-5"><h3 className="font-semibold">Manual triggers</h3><p className="text-sm text-brown-500">Force actions the schedule would otherwise run automatically.</p>
        <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>toast('Daily chart generation triggered for all open temples')} className="btn-g"><CalendarCheck size={16}/>Trigger today's charts now</button><button onClick={()=>toast('Payout batch generation triggered')} className="btn-g"><Landmark size={16}/>Trigger payout batch now</button><button onClick={()=>toast('Full backup started')} className="btn-g"><Database size={16}/>Run backup now</button></div></div>
      <div className={`card p-5 ${maint?'ring-2 ring-red-400':''}`}><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Site maintenance mode</h3><p className="text-sm text-brown-500">Shows a maintenance page to devotees; staff and vendor dashboards stay reachable. Use for deployments or emergency fixes.</p></div><Toggle label={maint?'Maintenance ON':'Off'} defaultChecked={maint} onChange={v=>{setMaint(v);toast(v?'Maintenance mode enabled — public site now shows the maintenance page':'Maintenance mode disabled — site is live')}}/></div>{maint&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">Public site is currently showing a maintenance page. Remember to turn this off before devotees are affected for long.</div>}</div>
    </div>}
  </SShell>)
}
export function STables() {
  return (<SShell><H t="Advanced · tables" s="Raw table browser for support and finance. Day-to-day work happens in the queues."/><input placeholder="Search tables…" className="input mb-4 !w-72"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Listings','1,304'],['Poojas','9,812'],['Bookings','38,411'],['Donations','2,190'],['PaymentTransactions','41,020'],['DailyCharts','6,730'],['VendorPayables','6,690'],['VendorPayouts','1,118'],['Subscriptions','214'],['Sponsors','61'],['Agents','190'],['Dealers','14'],['Wallets','204'],['WalletTransactions','3,301'],['OwnershipEvents','412'],['ExportJobs','412']].map(([t,n])=><div key={t} className="card p-4"><b className="text-sm">{t}</b><div className="text-xs text-brown-500">{n} rows</div></div>)}</div></SShell>)
}
