import React, { useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Wallet, Share2, PlusCircle, ListChecks, Map, Users, BarChart3, Inbox, ShieldCheck, CalendarCheck, Sparkles, Landmark, Banknote, HandCoins, Database, Settings2, Table2, ArrowRightLeft, Download, Upload, Check, Copy, Smartphone, MessageCircle, Globe, TrendingUp, IdCard, UserRound, ExternalLink, Pencil, Building2, FileText, UserPlus, Power } from 'lucide-react'
import { LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts'
import { temples, bySlug, analytics } from '../data'
import { DashShell, Pill, Field, Input, Select, Toggle, Table, Stat, Tabs, Steps, useToast } from '../ui'

const H = ({ t, s, right }) => <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t}</h1>{s&&<div className="text-sm text-brown-500">{s}</div>}</div>{right}</div>

/* ================= AGENT ================= */
const agentItems=[{group:'Agent',links:[['/agent','Wallet',Wallet],['/agent/profile','Profile & KYC',UserRound],['/agent/listings','My listings',ListChecks],['/agent/share','Share',Share2],['/agent/submit','Add listing',PlusCircle],['/agent/submissions','Submissions',ShieldCheck]]}]
const AgentIdentity = () => <span className="inline-flex items-center gap-2"><span>Jinsha</span><b className="rounded-full bg-gold-300 px-2.5 py-1 text-[11px] text-brown-900">AGENT ID · JIN-4471</b><b className="rounded-full border border-white/25 bg-white/10 px-2.5 py-1 text-[11px] text-gold-300">DEALER · KOZHIKODE NORTH</b></span>
const AShell = ({children}) => <DashShell role="Agent" user={<AgentIdentity/>} items={agentItems}>{children}</DashShell>

const downloadAgentId = () => {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1012" height="638" viewBox="0 0 1012 638"><rect width="1012" height="638" rx="42" fill="#2E2019"/><rect x="30" y="30" width="952" height="578" rx="28" fill="#F8F3EC"/><rect x="30" y="30" width="952" height="150" rx="28" fill="#4A3527"/><text x="75" y="95" font-family="serif" font-size="46" font-weight="700" fill="white">TempleAddress</text><text x="75" y="140" font-family="sans-serif" font-size="20" fill="#E4C77A">VERIFIED FIELD AGENT</text><circle cx="160" cy="310" r="82" fill="#E8722A"/><text x="160" y="330" text-anchor="middle" font-family="sans-serif" font-size="64" font-weight="700" fill="white">J</text><text x="285" y="270" font-family="serif" font-size="48" font-weight="700" fill="#2E2019">Jinsha</text><text x="285" y="320" font-family="sans-serif" font-size="26" fill="#7A5238">Agent ID: JIN-4471</text><text x="285" y="365" font-family="sans-serif" font-size="24" fill="#7A5238">Dealer: Kozhikode North · Rahul</text><rect x="75" y="440" width="862" height="95" rx="18" fill="#EFE4D6"/><text x="105" y="480" font-family="sans-serif" font-size="20" font-weight="700" fill="#2E2019">KYC VERIFIED · ACTIVE</text><text x="105" y="515" font-family="sans-serif" font-size="18" fill="#7A5238">Valid through 31 March 2027 · Verify at templeaddress.com/agent/JIN-4471</text></svg>`
  const url = URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})); const a=document.createElement('a'); a.href=url; a.download='TempleAddress-Agent-JIN-4471-ID.svg'; a.click(); URL.revokeObjectURL(url)
}

export function AWallet() {
  const [wd,setWd]=useState(false); const [toast,el]=useToast()
  return (<AShell>{el}<H t="Wallet" s={<span className="mt-1 flex flex-wrap gap-2"><b className="rounded-full bg-saffron-50 px-3 py-1 text-xs text-saffron-700">Agent ID · JIN-4471</b><b className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-800">Dealer · Kozhikode North (Rahul)</b></span>} right={<div className="flex flex-wrap gap-2"><button onClick={downloadAgentId} className="btn-g"><IdCard size={16}/>Download Agent ID</button><Link to="/agent/profile" className="btn-g"><UserRound size={16}/>Agent profile</Link><button onClick={()=>setWd(!wd)} className="btn-p"><Banknote size={16}/>Withdraw</button></div>}/>
    <div className="grid grid-cols-3 gap-3"><Stat v="₹6,840" l="available"/><Stat v="₹2,250" l="pending approval"/><Stat v="₹21,500" l="withdrawn so far"/></div>
    {wd && <div className="card mt-5 p-5"><h3 className="font-semibold">Withdraw to bank / UPI</h3><div className="mt-3 grid gap-4 md:grid-cols-2"><Field label="Amount ₹" hint="Minimum ₹500 · paid in the monthly cycle (next: 30 Sept)"><Input type="number" defaultValue="6840"/></Field><Field label="Pay to"><Select options={['UPI jinsha@okaxis','Federal Bank ····8821']}/></Field></div><p className="text-xs text-brown-500">TDS may be deducted as per rules; you'll get a statement.</p><button onClick={()=>{toast('Withdrawal of ₹6,840 requested');setWd(false)}} className="btn-p mt-3">Request ₹6,840</button></div>}
    <div className="card mt-5 p-5"><h3 className="font-semibold">Ledger</h3><Table head={['Date','For','Type','₹','Status']} rows={[['11 Sept','Resurge India Foundation → Kottur (Patron ₹30,000)','Sponsorship 15%','4,500',<Pill tone="ok">Approved</Pill>],['9 Sept','Vengamala Bhagavathi Temple','KYC done, bookings on','200',<Pill tone="ok">Approved</Pill>],['9 Sept','Vengamala Bhagavathi Temple','Listing approved','100',<Pill tone="ok">Approved</Pill>],['8 Sept','Special pooja via share link (×3)','5% of ₹4,500','225',<Pill tone="warn">Pending 15-day window</Pill>],['4 Sept','Prasad Nambeesan — Service Pro','15% of ₹3,000','450',<Pill tone="ok">Approved</Pill>],['2 Sept','Thrikapaleshwaram — Basic plan','15% of ₹6,000','900',<Pill tone="warn">Pending</Pill>],['30 Aug','Withdrawal · UTR FDRLN26242…','Paid out','−5,000',<Pill tone="ok">Paid</Pill>]]}/></div>
    <div className="card mt-5 p-5 text-sm"><b>Territory rates (Kozhikode North)</b><div className="text-brown-500">Listing approved ₹100 · KYC ₹200 · Plan 15% · Sponsorship 15% · Renewal 5% · Special pooja via your link 5% · Fee revenue from your listings 10% for 12 months</div></div></AShell>)
}

export function AProfile() {
  return (<AShell><H t="Agent profile & KYC" s={<span className="mt-1 flex flex-wrap gap-2"><b className="rounded-full bg-saffron-50 px-3 py-1 text-xs text-saffron-700">Agent ID · JIN-4471</b><b className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-800">Dealer · Kozhikode North (Rahul)</b></span>} right={<button onClick={downloadAgentId} className="btn-p"><Download size={16}/>Download Agent ID card</button>}/>
    <div className="grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="space-y-5"><div className="overflow-hidden rounded-2xl bg-brown-900 p-5 text-white shadow-soft"><div className="flex items-center justify-between"><span className="grid h-16 w-16 place-items-center rounded-full bg-saffron-500 text-2xl font-bold">J</span><Pill tone="ok"><ShieldCheck size={12}/>Active</Pill></div><h2 className="mt-5 text-2xl font-semibold">Jinsha</h2><p className="text-sm text-gold-300">TempleAddress Field Agent</p><div className="mt-4 rounded-xl bg-white/10 p-3"><div className="text-[11px] uppercase text-brown-200">Agent ID</div><div className="text-xl font-bold tracking-wider text-gold-300">JIN-4471</div></div><div className="mt-3 text-xs text-brown-100">KYC verified 18 March 2026<br/>Valid through 31 March 2027</div></div><div className="card p-5 text-sm"><b>Dealer relationship</b><p className="mt-2 text-brown-600">Kozhikode North territory</p><p className="text-brown-600">Dealer: <b>Rahul</b></p><p className="mt-2 text-xs text-brown-500">Pincodes 673001–673029</p></div></aside>
      <div className="space-y-5"><div className="card p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-lg font-semibold">Profile details</h3><Pill tone="ok">Verified</Pill></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Legal name','Jinsha P'],['Mobile','+91 98••• ••274'],['Email','jinsha@example.com'],['Address','Kozhikode, Kerala – 673011'],['PAN','ABCDE••••F'],['Aadhaar','XXXX XXXX 4821']].map(([k,v])=><div key={k}><dt className="text-xs font-semibold uppercase text-brown-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl></div>
      <div className="card p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-lg font-semibold">Settlement details</h3><Pill tone="ok">Penny-drop verified</Pill></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Bank','Federal Bank'],['Account','XXXXXXXX8821'],['IFSC','FDRL0001234'],['UPI ID','jinsha@okaxis']].map(([k,v])=><div key={k}><dt className="text-xs font-semibold uppercase text-brown-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl></div>
      <div className="card p-5"><h3 className="text-lg font-semibold">KYC documents</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{['Agent photograph','Aadhaar copy','PAN card copy','Bank passbook copy'].map(x=><div key={x} className="flex items-center gap-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><Check size={16}/><span className="flex-1">{x}</span><b>Verified</b></div>)}</div><p className="mt-3 text-xs text-brown-500">KYC documents are read-only after verification. Contact your dealer or TempleAddress staff to request a correction.</p></div></div></div>
  </AShell>)
}

export function AListings() {
  const listings = [
    [temples[2],'Owner · submitted by you','Verified · bookings on','ok','₹300'],
    [temples[0],'Transferred to committee','Verified · Pro','ok','₹4,800'],
    [temples[3],'Referral listing','Edit awaiting staff review','warn','₹900'],
  ]
  return (<AShell><H t="My listings" s="View public pages in a new tab or submit edits for staff approval" right={<Link to="/agent/submit" className="btn-p"><PlusCircle size={16}/>Add temple</Link>}/><div className="space-y-4">{listings.map(([t,ownership,state,tone,earned])=><article key={t.slug} className="card p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{t.name}</h2><Pill tone={tone}>{state}</Pill></div><div className="ml mt-0.5 text-sm text-brown-500">{t.ml}</div><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-brown-500"><span>{t.code} · {t.place}, {t.district}</span><span>{ownership}</span><span>Earned: <b className="text-brown-800">{earned}</b></span></div></div><div className="flex flex-col gap-2 sm:flex-row"><a href={`#\/t/${t.slug}`} target="_blank" rel="noopener noreferrer" className="btn-g"><ExternalLink size={16}/>Detailed view</a><Link to={`/agent/listings/${t.slug}/edit`} className="btn-s"><Pencil size={16}/>Edit listing</Link></div></div>{tone==='warn'&&<div className="mt-4 rounded-xl bg-saffron-50 p-3 text-xs text-saffron-800"><b>Staff approval pending.</b> Your requested timing and history changes are being reviewed. The currently approved public page remains live until approval.</div>}</article>)}</div></AShell>)
}

function ListingForm({existing,onSubmit,cancelTo='/agent/listings'}) {
  const [step,setStep]=useState(0); const [type,setType]=useState(existing?'Temple':'Temple'); const [cover,setCover]=useState(0); const [verified,setVerified]=useState(true); const [toast,el]=useToast()
  const steps=['Type & basics','Location','Details','Gallery','Contact & KYC','Review']
  const name=existing?.name||''; const ml=existing?.ml||''
  return (<>{el}<Steps items={steps} at={step}/><div className="card space-y-5 p-4 sm:p-6">
    {step===0&&<><div><h2 className="text-xl font-semibold">Listing type & basics</h2><p className="text-sm text-brown-500">Agents may create temples, festivals, service professionals and special poojas.</p></div><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{['Temple','Festival','Service professional','Special pooja'].map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-xl border p-3 text-sm font-semibold ${type===x?'border-saffron-500 bg-saffron-50 text-saffron-700':'border-brown-200 bg-white'}`}>{x}</button>)}</div><div className="grid gap-4 md:grid-cols-2"><Field label={`${type} name (English)`}><Input defaultValue={name} placeholder={type==='Temple'?'Sree … Temple':`${type} name`}/></Field><Field label={`${type} name (Malayalam)`}><Input defaultValue={ml} placeholder="Malayalam name"/></Field><Field label="Category"><Select options={type==='Temple'?['Temple','Kavu','Church','Mosque','Holy place']:type==='Service professional'?['Poojari','Astrologer','Temple artist','Musician','Other service']:type==='Festival'?['Temple festival','Utsavam','Community festival']:['Homam','Pooja','Offering','Group ritual']}/></Field><Field label="Public listing code"><Input defaultValue={existing?.code||'Generated after approval'} disabled/></Field>
      {type==='Temple'&&<><Field label="Main deity"><Input defaultValue={existing?.deity}/></Field><Field label="Other deities / Upadevathas"><Input defaultValue={existing?.others?.join(', ')}/></Field><Field label="Managed by"><Select options={['Committee','Devaswom board','Family / Illam','Registered trust']}/></Field><Field label="Temple timings"><Input defaultValue={existing?.timings} placeholder="5:30–9:30 AM · 5:30–7:30 PM"/></Field></>}
      {type==='Festival'&&<><Field label="Organising temple / committee"><Input/></Field><Field label="Festival dates"><Input placeholder="Start date – end date"/></Field><Field label="Venue"><Input/></Field><Field label="Sponsorship available"><Select options={['Yes','No']}/></Field></>}
      {type==='Service professional'&&<><Field label="Profession / service type"><Input placeholder="Poojari, astrologer, artist…"/></Field><Field label="Years of experience"><Input type="number"/></Field><Field label="Qualifications"><Input/></Field><Field label="Languages"><Input placeholder="Malayalam, English…"/></Field></>}
      {type==='Special pooja'&&<><Field label="Host temple / provider"><Input/></Field><Field label="Date or frequency"><Input placeholder="14 Sept or Every Friday"/></Field><Field label="Price ₹"><Input type="number"/></Field><Field label="Maximum bookings / seats"><Input type="number"/></Field><Field label="Proof provided"><Select options={['Photo + video','Photo','Video','None']}/></Field><Field label="Prasadam delivery"><Select options={['Collection','Post / courier','Not applicable']}/></Field></>}
    </div></>}
    {step===1&&<><div><h2 className="text-xl font-semibold">Location & directions</h2><p className="text-sm text-brown-500">Provide enough detail for devotees and staff verification.</p></div><div className="grid gap-4 md:grid-cols-2"><Field label="State"><Select options={['Kerala','Tamil Nadu','Karnataka','Other']}/></Field><Field label="District"><Select options={['Kozhikode','Thiruvananthapuram','Malappuram','Thrissur','Pathanamthitta','Other']}/></Field><Field label="Panchayat / town"><Input defaultValue={existing?.place}/></Field><Field label="Pincode"><Input inputMode="numeric"/></Field><Field label="Full address" className="md:col-span-2"><textarea className="input" rows={3} defaultValue={existing?.address}/></Field><Field label="Google Maps link"><Input placeholder="https://maps.google.com/…"/></Field><Field label="Latitude / longitude"><Input placeholder="11.2588, 75.7804"/></Field></div><button onClick={()=>toast('Location captured for this prototype')} className="btn-g">Use my current location</button><div className="photo aspect-[16/5] rounded-xl"/></>}
    {step===2&&<><div><h2 className="text-xl font-semibold">Public listing details</h2><p className="text-sm text-brown-500">These fields appear on the detailed listing page after approval.</p></div><Field label="About"><textarea className="input" rows={4} defaultValue={existing?.about}/></Field>{type==='Temple'&&<><Field label="Story / Aithihyam"><textarea className="input" rows={3} defaultValue={existing?.story}/></Field><Field label="History"><textarea className="input" rows={3} defaultValue={existing?.history}/></Field><Field label="Speciality"><textarea className="input" rows={3} defaultValue={existing?.speciality}/></Field><Field label="Other deities"><textarea className="input" rows={2} defaultValue={existing?.others?.join(', ')}/></Field></>}<Field label={type==='Festival'?'Programme and schedule':type==='Service professional'?'Services, prices and availability':type==='Special pooja'?'Ritual details and devotee instructions':'Guidelines for devotees'}><textarea className="input" rows={4} defaultValue={existing?.guidelines}/></Field><Field label="Remarks"><textarea className="input" rows={2} defaultValue={existing?.remarks}/></Field><Field label="Nearby places to visit" hint="One place per line, including distance"><textarea className="input" rows={3} defaultValue={existing?.nearby?.join('\n')}/></Field>{type==='Temple'&&<div className="rounded-xl bg-brown-50 p-4"><h3 className="font-semibold">Poojas / Vazhipadu</h3><div className="mt-3 grid gap-3 md:grid-cols-4"><Input placeholder="Pooja name"/><Input placeholder="Malayalam name"/><Input type="number" placeholder="Price ₹"/><Input type="number" placeholder="Daily limit"/></div><button className="btn-g mt-3">+ Add another pooja</button></div>}</>}
    {step===3&&<><div><h2 className="text-xl font-semibold">Gallery & cover image</h2><p className="text-sm text-brown-500">Upload clear, recent images and select exactly one default cover photo.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[0,1,2,3].map(i=><label key={i} className={`relative overflow-hidden rounded-2xl border-2 ${cover===i?'border-saffron-500 ring-2 ring-saffron-100':'border-brown-200'}`}><div className="photo aspect-square p-3 text-white"><span className="pill bg-black/30">{i===0&&existing?'Current photo':`Photo ${i+1}`}</span></div><div className="space-y-2 bg-white p-3"><input type="file" accept="image/*" className="block w-full text-[10px]"/><label className="flex items-center gap-2 text-xs font-semibold"><input type="radio" name="cover" checked={cover===i} onChange={()=>setCover(i)}/>Default cover</label></div></label>)}</div><button className="btn-g">+ Add more gallery photos</button><p className="text-xs text-brown-500">For temples, include the entrance or sreekovil exterior. Do not upload restricted sanctum photography.</p></>}
    {step===4&&<><div><h2 className="text-xl font-semibold">Contact, registration & settlement</h2><p className="text-sm text-brown-500">Required for verified listings and online collections.</p></div><Toggle label="Apply for a verified listing" defaultChecked={verified} onChange={setVerified}/><div className="grid gap-4 md:grid-cols-2"><Field label="Authorised contact / secretary"><Input/></Field><Field label="Role / designation"><Input placeholder="Secretary, trustee, owner…"/></Field><Field label="WhatsApp number"><Input placeholder="+91"/></Field><Field label="Email"><Input type="email"/></Field><Field label="PAN card number"><Input placeholder="AAATK1234B"/></Field><Field label="Registration number"><Input placeholder="Trust / committee / society registration"/></Field><Field label="Bank account number"><Input/></Field><Field label="IFSC"><Input placeholder="FDRL0001234"/></Field><Field label="Bank and branch"><Input placeholder="Federal Bank · Ulliyeri branch"/></Field><Field label="UPI ID"><Input placeholder="listing@bank"/></Field></div>{verified&&<div className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><h3 className="font-semibold text-blue-900">Documents required for verification</h3><p className="mt-1 text-xs text-blue-800">Staff will verify these before awarding the verified badge or enabling bookings.</p><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="PAN card copy"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="Bank account proof" hint="Passbook or statement showing account details"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="Authorisation letter / contract" hint="Trust or committee authority and TempleAddress contract agreement"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="Registration certificate"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="Signatory ID proof"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field></div></div>}</>}
    {step===5&&<div className="space-y-4"><div className="rounded-2xl bg-emerald-50 p-5 text-sm text-emerald-800"><div className="flex items-center gap-2"><ShieldCheck size={20}/><b>Ready for staff verification</b></div><p className="mt-2">Submitting creates a pending revision. Staff reviews the listing content, selected cover image, gallery, registration information, bank details and verification documents.</p></div><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-brown-50 p-4"><b>Listing type</b><p className="text-sm text-brown-500">{type}</p></div><div className="rounded-xl bg-brown-50 p-4"><b>Cover image</b><p className="text-sm text-brown-500">Gallery photo {cover+1}</p></div><div className="rounded-xl bg-brown-50 p-4"><b>Verification</b><p className="text-sm text-brown-500">{verified?'Requested · documents included':'Not requested'}</p></div></div>{existing&&<Field label="Reason for editing" hint="Required for the staff reviewer"><textarea className="input" rows={3} placeholder="Describe what changed and why"/></Field>}</div>}
    <div className="flex flex-col-reverse gap-2 border-t border-brown-100 pt-5 sm:flex-row sm:justify-between"><button onClick={()=>toast(`${type} saved as draft`)} className="btn-g">Save draft</button><div className="flex gap-2">{step>0&&<button onClick={()=>setStep(s=>s-1)} className="btn-g">Back</button>}{step<steps.length-1?<button onClick={()=>setStep(s=>s+1)} className="btn-p flex-1">Next</button>:<button onClick={onSubmit} className="btn-p flex-1"><ShieldCheck size={16}/>{existing?'Submit changes for approval':'Submit listing for verification'}</button>}<Link to={cancelTo} className="btn-g">Cancel</Link></div></div>
  </div></>)
}

export function AEditListing() {
  const {slug}=useParams(); const t=bySlug(slug); const [submitted,setSubmitted]=useState(false)
  if(submitted) return (<AShell><div className="mx-auto max-w-2xl py-10"><div className="card p-8 text-center"><ShieldCheck size={44} className="mx-auto text-saffron-600"/><Pill tone="warn">Staff approval pending</Pill><h1 className="mt-3 text-2xl font-semibold">Listing changes submitted</h1><p className="mt-2 text-sm text-brown-500">The currently approved version of {t.name} stays public while staff reviews your edits. Feedback will appear in My listings and Submissions.</p><div className="mt-5 flex flex-wrap justify-center gap-2"><Link to="/agent/listings" className="btn-p">Back to my listings</Link><a href={`#\/t/${t.slug}`} target="_blank" rel="noopener noreferrer" className="btn-g"><ExternalLink size={16}/>View live listing</a></div></div></div></AShell>)
  return (<AShell><H t={`Edit · ${t.name}`} s="The edit form includes every field available during creation. The live listing stays unchanged until staff approval." right={<a href={`#\/t/${t.slug}`} target="_blank" rel="noopener noreferrer" className="btn-g"><ExternalLink size={16}/>View live page</a>}/>
    <div className="mb-5 rounded-2xl border border-saffron-100 bg-saffron-50 p-4 text-sm text-saffron-800"><b>Staff approval required.</b> You can save this revision as a draft or submit it for moderation. Visitors continue seeing the last approved version.</div>
    <ListingForm existing={t} onSubmit={()=>setSubmitted(true)}/>
  </AShell>)
}

export function AShare() {
  const [toast,el]=useToast()
  return (<AShell>{el}<H t="Share & promote" s="Every link carries your code JIN-4471 · 30-day attribution"/>
    <div className="card p-5"><Field label="What to share"><Select options={['Kottur Sree Mahavishnu Temple','Special: Ashta Dravya Maha Ganapathi Homam · 14 Sept','Sponsor a temple','Vengamala Bhagavathi Temple']}/></Field><div className="mt-2 flex items-center gap-2 rounded-xl bg-brown-50 px-3 py-2"><code className="flex-1 text-sm">https://kottur.templeaddress.com/?ref=JIN-4471</code><button onClick={()=>toast('Copied')} className="btn-g !py-1.5"><Copy size={14}/>Copy</button></div>
      <div className="mt-3 flex flex-wrap gap-2"><button className="btn-wa"><MessageCircle size={16}/>WhatsApp</button><button className="btn-s">Facebook</button><button className="btn-s">Instagram story</button><button className="btn-g">X</button><button className="btn-g"><Share2 size={16}/>Share…</button></div></div>
    <div className="mt-5 grid gap-5 md:grid-cols-2"><div className="card p-5"><h3 className="font-semibold">Poster for WhatsApp status</h3><div className="photo mt-2 aspect-[9/16] max-w-[200px] rounded-xl p-3 text-xs text-white">Kottur Sree Mahavishnu Temple<br/>Book pooja online<br/>QR · JIN-4471</div><button className="btn-g mt-2"><Download size={16}/>Download poster</button></div>
      <div className="card p-5"><h3 className="font-semibold">Pre-filled message</h3><textarea rows={6} className="input mt-2" defaultValue={'🙏 Kottur Sree Mahavishnu Temple is now online. Book Ganapathi Homam, Pushpanjali and more — receipt on WhatsApp, 100% goes to the temple.\nkottur.templeaddress.com/?ref=JIN-4471'}/><span className="text-xs text-brown-500">Malayalam version available</span></div></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Results this month</h3><Table head={['Link','Clicks','Bookings','Plans / sponsors','Earned ₹']} rows={[['Kottur temple','312','19','1 sponsor','4,500'],['Ashta Dravya Homam','148','3','—','225'],['Sponsor a temple','41','—','—','—']]}/></div></AShell>)
}
export function ASubmit() {
  const [submitted,setSubmitted]=useState(false)
  if(submitted) return (<AShell><div className="mx-auto max-w-2xl py-10"><div className="card p-8 text-center"><ShieldCheck size={44} className="mx-auto text-emerald-600"/><Pill tone="warn">Pending staff verification</Pill><h1 className="mt-3 text-2xl font-semibold">New listing submitted</h1><p className="mt-2 text-sm text-brown-500">Staff will review the listing, gallery cover, registration details, bank information and verification documents before publishing it.</p><Link to="/agent/submissions" className="btn-p mt-5">View submission status</Link></div></div></AShell>)
  return (<AShell><H t="Create a new listing" s="Temple · Festival · Service professional · Special pooja"/><ListingForm onSubmit={()=>setSubmitted(true)} cancelTo="/agent"/></AShell>)
}
export function ASubmissions() {
  return (<AShell><H t="My submissions" s="Temples, festivals, service professionals and special poojas"/><div className="card p-4"><Table head={['Listing','Submitted','Status','Owner / feedback','Earned']} rows={[['Vengamala Bhagavathi Temple','2 Sept',<Pill tone="ok">Verified · bookings on</Pill>,'Agent (you) → claim pending by secretary','₹300'],['Kottur Sree Mahavishnu Temple','4 Jul',<Pill tone="ok">Verified · Pro</Pill>,'Transferred to committee 2 Aug','₹4,800'],['Sree Neelakeshi Mudippura Temple','9 Sept',<Pill tone="warn">Pending review</Pill>,'—','—'],['Vithura Sree Mahadeva Temple','6 Sept',<Pill tone="err">Needs changes</Pill>,'Staff: history & guidelines missing','—']]}/></div></AShell>)
}

/* ================= DEALER ================= */
const dealerItems=[{group:'Dealer',links:[['/dealer','Territory',Map],['/dealer/profile','Profile & KYC',Building2],['/dealer/agents','Agents',Users],['/agent','My wallet',Wallet]]}]
const DShell = ({children}) => <DashShell role="Dealer" user={<span className="inline-flex items-center gap-2"><span>Rahul</span><b className="rounded-full bg-gold-300 px-2.5 py-1 text-[11px] text-brown-900">DEALER · KOZHIKODE NORTH</b></span>} items={dealerItems}>{children}</DashShell>

const downloadDealerFile = (name,type,content) => { const url=URL.createObjectURL(new Blob([content],{type})); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url) }
const dealerAgreement = `<!doctype html><html><head><meta charset="utf-8"><title>TempleAddress Dealership Agreement</title><style>body{font-family:Arial;max-width:760px;margin:50px auto;line-height:1.6;color:#2e2019}h1{border-bottom:3px solid #e8722a;padding-bottom:12px}.box{background:#f8f3ec;padding:18px;border-radius:12px}</style></head><body><h1>TempleAddress Dealership Agreement</h1><div class="box"><b>Dealer:</b> Malabar Digital Services<br><b>Territory:</b> Kozhikode North · Pincodes 673001–673029<br><b>Dealer ID:</b> DLR-KZN-014<br><b>Effective:</b> 1 March 2026 · <b>Valid through:</b> 28 February 2027</div><p>This agreement authorises the dealer to invite, enable, supervise and disable TempleAddress field agents in the assigned territory, subject to platform KYC, listing verification and conduct policies.</p><p>Signed electronically by TempleAddress and Rahul K, Authorised Partner.</p></body></html>`
const dealerCertificate = `<svg xmlns="http://www.w3.org/2000/svg" width="1120" height="790"><rect width="1120" height="790" fill="#2E2019"/><rect x="34" y="34" width="1052" height="722" rx="30" fill="#F8F3EC"/><rect x="58" y="58" width="1004" height="674" rx="22" fill="none" stroke="#C99A3C" stroke-width="5"/><text x="560" y="155" text-anchor="middle" font-family="serif" font-size="54" font-weight="700" fill="#2E2019">TempleAddress</text><text x="560" y="218" text-anchor="middle" font-family="sans-serif" font-size="24" fill="#E8722A">CERTIFICATE OF AUTHORISED DEALERSHIP</text><text x="560" y="315" text-anchor="middle" font-family="serif" font-size="30" fill="#7A5238">This certifies that</text><text x="560" y="390" text-anchor="middle" font-family="serif" font-size="52" font-weight="700" fill="#2E2019">Malabar Digital Services</text><text x="560" y="445" text-anchor="middle" font-family="sans-serif" font-size="25" fill="#7A5238">Rahul K · Dealer ID DLR-KZN-014</text><text x="560" y="510" text-anchor="middle" font-family="sans-serif" font-size="24" fill="#2E2019">is the authorised TempleAddress dealer for Kozhikode North</text><text x="560" y="555" text-anchor="middle" font-family="sans-serif" font-size="21" fill="#7A5238">Pincodes 673001–673029 · Valid through 28 February 2027</text><circle cx="560" cy="650" r="42" fill="#E8722A"/><text x="560" y="660" text-anchor="middle" font-family="sans-serif" font-size="24" font-weight="700" fill="white">TA</text></svg>`

export function DProfile() {
  const [editing,setEditing]=useState(false); const [agreement,setAgreement]=useState(false); const [toast,el]=useToast()
  return (<DShell>{el}<H t="Dealer profile & KYC" s={<span className="mt-1 flex flex-wrap gap-2"><b className="rounded-full bg-saffron-50 px-3 py-1 text-xs text-saffron-700">Dealer ID · DLR-KZN-014</b><b className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-800">Territory · Kozhikode North</b></span>} right={<button onClick={()=>setEditing(v=>!v)} className="btn-p"><Pencil size={16}/>{editing?'Close editor':'Update dealer profile'}</button>}/>
    <div className="grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="space-y-5"><div className="overflow-hidden rounded-2xl bg-brown-900 p-5 text-white"><div className="flex items-center justify-between"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-saffron-500 text-2xl font-bold">MD</span><Pill tone="ok"><ShieldCheck size={12}/>Active dealer</Pill></div><h2 className="mt-5 text-2xl font-semibold">Malabar Digital Services</h2><p className="text-sm text-gold-300">Authorised TempleAddress Dealership</p><div className="mt-4 rounded-xl bg-white/10 p-3"><div className="text-[11px] uppercase text-brown-200">Dealer ID</div><div className="text-xl font-bold text-gold-300">DLR-KZN-014</div></div><p className="mt-3 text-xs text-brown-100">Kozhikode North · 14 agents<br/>Agreement valid to 28 Feb 2027</p></div><div className="card p-5"><h3 className="font-semibold">Documents</h3><div className="mt-3 space-y-2"><button onClick={()=>setAgreement(v=>!v)} className="btn-g w-full"><FileText size={16}/>{agreement?'Hide':'View'} agreement</button><button onClick={()=>downloadDealerFile('TempleAddress-Dealership-Agreement-DLR-KZN-014.html','text/html',dealerAgreement)} className="btn-g w-full"><Download size={16}/>Download agreement</button><button onClick={()=>downloadDealerFile('TempleAddress-Dealer-Certificate-DLR-KZN-014.svg','image/svg+xml',dealerCertificate)} className="btn-p w-full"><Download size={16}/>Download certificate</button></div></div></aside>
      <div className="space-y-5">{editing?<div className="card p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">Update dealer profile</h3><Pill tone="warn">Changes require staff review</Pill></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Legal entity name"><Input defaultValue="Malabar Digital Services"/></Field><Field label="Registration number"><Input defaultValue="KL/KKD/2026/0142"/></Field><Field label="Office address" className="md:col-span-2"><textarea className="input" rows={3} defaultValue="2nd Floor, City Tower, Nadakkavu, Kozhikode, Kerala – 673011"/></Field><Field label="Business email"><Input type="email" defaultValue="office@malabardigital.example"/></Field><Field label="Office phone number"><Input type="tel" defaultValue="+91 495 27 44 810"/></Field><Field label="Primary contact person"><Input defaultValue="Rahul K"/></Field><Field label="Designation"><Input defaultValue="Managing Partner"/></Field><Field label="Contact role"><Select options={['Dealer owner · Full access','Operations · Agent management','Finance · Wallet and reports']}/></Field><Field label="Contact mobile"><Input defaultValue="+91 98••• ••9902"/></Field><Field label="Additional contact person"><Input placeholder="Name"/></Field><Field label="Additional contact designation / role"><Input placeholder="Operations manager"/></Field><Field label="Registration certificate"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="Updated address proof"><Input type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field></div><div className="mt-5 flex gap-2"><button onClick={()=>{toast('Dealer profile update submitted for staff review');setEditing(false)}} className="btn-p"><ShieldCheck size={16}/>Submit profile update</button><button onClick={()=>setEditing(false)} className="btn-g">Cancel</button></div></div>:<><div className="card p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">Business profile</h3><Pill tone="ok">KYC verified</Pill></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Legal entity','Malabar Digital Services'],['Registration no.','KL/KKD/2026/0142'],['Office address','2nd Floor, City Tower, Nadakkavu, Kozhikode – 673011'],['Business email','office@malabardigital.example'],['Office number','+91 495 27 44 810'],['Territory','Kozhikode North · 673001–673029']].map(([k,v])=><div key={k}><dt className="text-xs font-semibold uppercase text-brown-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl></div><div className="card p-5"><h3 className="text-lg font-semibold">Authorised contacts</h3><Table head={['Person','Designation','Role','Contact','Status']} rows={[["Rahul K","Managing Partner","Dealer owner · Full access","+91 98••• ••9902",<Pill tone="ok">Verified</Pill>],["Deepa Menon","Operations Manager","Agent management","deepa@malabardigital.example",<Pill tone="ok">Active</Pill>]]}/></div></>}
      <div className="card p-5"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">KYC & settlement</h3><Pill tone="ok">Verified 1 Mar 2026</Pill></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Entity PAN','AABCM••••K'],['GSTIN','32AABCM1234K1Z8'],['Bank','Federal Bank · Nadakkavu'],['Account','XXXXXXXX9902'],['IFSC','FDRL0001412'],['Agreement','Signed · AGR-DLR-2026-014']].map(([k,v])=><div key={k}><dt className="text-xs font-semibold uppercase text-brown-500">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl><div className="mt-4 grid gap-2 sm:grid-cols-3">{['Registration certificate','PAN copy','Bank account proof'].map(x=><div key={x} className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><Check size={14} className="mr-1 inline"/>{x}<b className="block text-xs">Verified</b></div>)}</div></div></div></div>
    {agreement&&<div className="card mt-5 p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Dealership agreement</h2><Pill tone="ok">Signed electronically</Pill></div><div className="mt-4 rounded-xl bg-brown-50 p-5 text-sm leading-relaxed text-brown-700"><b>Agreement AGR-DLR-2026-014</b><p className="mt-2">TempleAddress appoints Malabar Digital Services, represented by Rahul K, as the authorised dealer for Kozhikode North (pincodes 673001–673029) from 1 March 2026 through 28 February 2027.</p><p className="mt-2">The dealer may invite and supervise field agents. Only enabled, KYC-approved agents may work, submit listings or earn referral rewards. The dealer must disable access promptly when an agent leaves or breaches policy.</p></div></div>}
  </DShell>)
}

export function DDash() {
  return (<DShell><H t="Kozhikode North" s="Pincodes 673001–673029 · 14 agents" right={<div className="flex gap-2"><Link to="/dealer/profile" className="btn-g"><Building2 size={16}/>Dealer profile</Link><Link to="/agent" className="btn-p"><Wallet size={16}/>My wallet · ₹18,320</Link></div>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat v="86" l="temples live"/><Stat v="21" l="paying / sponsored"/><Stat v="₹2,64,000" l="territory revenue YTD"/><Stat v="₹13,200" l="override this month"/></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_320px]"><div className="card p-5"><h3 className="font-semibold">Agents</h3><Table head={['Agent','Listings','Verified','Plans + sponsors','This month ₹']} rows={[['Jinsha (JIN-4471)','23','19','4','6,375'],['Arun (ARU-2210)','17','14','2','2,100'],['Sangeetha (SAN-0932)','11','9','3','4,950'],['Faisal (FAI-1187)','4','2','0','200']]}/><Link to="/dealer/agents" className="mt-2 block text-sm text-saffron-600">All 14 agents</Link></div>
      <aside className="space-y-4"><div className="card p-5 text-sm"><b>Expiring in 30 days</b><div className="mt-1 text-brown-600">Thrikapaleshwaram — Basic (28 Sept)<br/>Prasad Nambeesan — Service Pro (4 Oct)</div><div className="mt-1 text-xs text-brown-500">Renewal earns 5% agent + 2% dealer</div></div><div className="card p-5 text-sm"><b>Pending agent requests</b><div className="text-brown-600">2 new agents want to join · <Link to="/dealer/agents" className="text-saffron-600">Review</Link></div></div></aside></div></DShell>)
}
export function DAgents() {
  const [invite,setInvite]=useState(false); const [toast,el]=useToast()
  const [inviteData,setInviteData]=useState({name:'',phone:'',email:''})
  const [agents,setAgents]=useState([{name:'Jinsha',code:'JIN-4471',joined:'Mar 2026',listings:23,earned:'₹28,340',enabled:true},{name:'Arun',code:'ARU-2210',joined:'Apr 2026',listings:17,earned:'₹12,100',enabled:true},{name:'Sangeetha',code:'SAN-0932',joined:'May 2026',listings:11,earned:'₹15,900',enabled:true},{name:'Faisal',code:'FAI-1187',joined:'Jun 2026',listings:4,earned:'₹2,100',enabled:false}])
  const toggleAgent = code => setAgents(xs=>xs.map(a=>a.code===code?{...a,enabled:!a.enabled}:a))
  return (<DShell>{el}<H t="Agents · Kozhikode North" s="Only enabled agents can access agent tools, submit listings or start work" right={<button onClick={()=>setInvite(v=>!v)} className="btn-p"><UserPlus size={16}/>Invite user as agent</button>}/>
    {invite&&<div className="card mb-5 p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Invite a user as agent</h2><p className="text-sm text-brown-500">Enter the user’s name and either a phone number or email address.</p></div><Pill tone="info">Dealer invitation</Pill></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Name" className="md:col-span-2"><Input value={inviteData.name} onChange={e=>setInviteData({...inviteData,name:e.target.value})} placeholder="Full name" required/></Field><Field label="Phone number" hint="Phone or email is required"><Input type="tel" value={inviteData.phone} onChange={e=>setInviteData({...inviteData,phone:e.target.value})} placeholder="+91"/></Field><Field label="Email address" hint="Phone or email is required"><Input type="email" value={inviteData.email} onChange={e=>setInviteData({...inviteData,email:e.target.value})} placeholder="user@example.com"/></Field></div><div className="mt-4 rounded-xl bg-blue-50 p-3 text-xs text-blue-900">The invited user must accept, complete KYC, and then be <b>enabled by the dealer</b>. Until enabled, the agent cannot access work tools.</div><div className="mt-4 flex gap-2"><button disabled={!inviteData.name.trim()||(!inviteData.phone.trim()&&!inviteData.email.trim())} onClick={()=>{toast('Agent invitation sent');setInvite(false);setInviteData({name:'',phone:'',email:''})}} className="btn-p">Send invitation</button><button onClick={()=>setInvite(false)} className="btn-g">Cancel</button></div></div>}
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Stat v={agents.filter(a=>a.enabled).length} l="enabled · can work"/><Stat v={agents.filter(a=>!a.enabled).length} l="disabled · access blocked"/><Stat v="2" l="invites / approvals pending"/></div>
    <div className="card p-4"><Table head={['Agent','Joined','Listings','Earned YTD','Access status','Action']} rows={agents.map(a=>[<span><b>{a.name}</b><span className="block text-xs text-brown-500">{a.code}</span></span>,a.joined,a.enabled?a.listings:'—',a.enabled?a.earned:'—',a.enabled?<Pill tone="ok">Enabled · can work</Pill>:<Pill tone="err">Disabled · access blocked</Pill>,<button onClick={()=>{toggleAgent(a.code);toast(`${a.name} ${a.enabled?'disabled — work access blocked':'enabled — can start working'}`)}} className={`btn !px-3 !py-1.5 text-xs ${a.enabled?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}><Power size={13}/>{a.enabled?'Disable':'Enable'}</button>])}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Pending agent requests</h3><Table head={['User','Contact','Requested','KYC','Dealer action']} rows={[[<b>Meera P</b>,'+91 98••• ••411 · meera@example.com','10 Sept',<Pill tone="ok">Verified</Pill>,<span className="flex gap-2"><button onClick={()=>toast('Meera enabled and can start working')} className="font-semibold text-emerald-700">Enable agent</button><button className="text-red-600">Reject</button></span>],[<b>Sudheesh K</b>,'+91 97••• ••882','11 Sept',<Pill tone="warn">Documents pending</Pill>,<span className="text-brown-500">Wait for KYC</span>]]}/><p className="mt-3 text-xs text-brown-500">Disabling an agent immediately blocks agent-dashboard access and new work. Existing submissions and audit history remain available to the dealer and staff.</p></div>
  </DShell>)
}

/* ================= STAFF / SUPER ADMIN ================= */
// Staff is split into three sub-roles, chosen at login (?role= on every /staff* URL):
//  · moderator  — reviews listings, temples, service providers, agents, bookings & daily charts
//  · accountant — financial reports, vendor/agent/dealer payouts, manual NEFT sheet
//  · admin      — Portal admin: settings, approvals for staff/accountant/dealer, KYC & fee config, maintenance mode
const staffNav = role => {
  const q = `?role=${role}`
  if (role==='moderator') return [{group:'Moderation',links:[['/staff'+q,'Queues',Inbox],['/staff/listing'+q,'Listing review',ListChecks],['/staff/kyc'+q,'KYC',ShieldCheck],['/staff/charts'+q,'Daily charts',CalendarCheck],['/staff/special'+q,'Special poojas',Sparkles],['/staff/ownership'+q,'Claims & transfers',ArrowRightLeft]]}]
  if (role==='accountant') return [{group:'Finance',links:[['/staff'+q,'Queues',Inbox],['/staff/payouts'+q,'Payouts',Landmark],['/staff/withdrawals'+q,'Wallet withdrawals',HandCoins],['/staff/sponsors'+q,'Sponsors & plans',Banknote],['/staff/analytics'+q,'Analytics',BarChart3]]}]
  return [{group:'Work queues',links:[['/staff'+q,'Queues',Inbox],['/staff/analytics'+q,'Analytics',BarChart3],['/staff/payouts'+q,'Payouts',Landmark],['/staff/listing'+q,'Listing review',ListChecks],['/staff/kyc'+q,'KYC',ShieldCheck],['/staff/charts'+q,'Charts',CalendarCheck],['/staff/special'+q,'Special poojas',Sparkles],['/staff/withdrawals'+q,'Wallet withdrawals',HandCoins],['/staff/ownership'+q,'Claims & transfers',ArrowRightLeft],['/staff/sponsors'+q,'Sponsors & plans',Banknote],['/staff/backup'+q,'Backup & restore',Database]]},{group:'Portal admin',links:[['/staff/config'+q,'Configuration',Settings2],['/staff/tables'+q,'Advanced → tables',Table2]]}]
}
const staffRoleLabel = {moderator:'Staff · Moderator', accountant:'Staff · Accountant', admin:'Staff · Portal admin'}
const SShell = ({children}) => { const [sp]=useSearchParams(); const role = staffRoleLabel[sp.get('role')] ? sp.get('role') : 'admin'
  return <DashShell role={staffRoleLabel[role]} user="Anand · Admin" items={staffNav(role)} badge="24">{children}</DashShell> }
const Q = ({c,t,s,h,hot}) => <Link to={h} className="card flex items-center gap-3 p-4 transition hover:shadow-soft"><span className={`grid h-11 w-11 place-items-center rounded-xl text-lg font-bold ${hot?'bg-saffron-50 text-saffron-600':'bg-brown-50 text-brown-800'}`}>{c}</span><span className="flex-1"><b className="block text-sm">{t}</b><span className="text-xs text-brown-500">{s}</span></span><span className="btn-g !py-1.5 text-xs">Open</span></Link>

export function SQueues() {
  return (<SShell><H t="Work queues" s="Fri 11 Sept 2026, 11:20 AM" right={<Link to="/staff/analytics" className="btn-g"><BarChart3 size={16}/>Analytics</Link>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat v="1,240" l="verified temples" delta="+38 this week"/><Stat v="168" l="bookings today"/><Stat v="₹46,300" l="payable to temples"/><Stat v="₹1,12,400" l="revenue this month" delta="+22% vs Aug"/></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2"><Q c={12} t="Pending listings" s="oldest 4 days · 3 from agents" h="/staff/listing" hot/><Q c={5} t="KYC to review" s="2 with 80G certificates" h="/staff/kyc" hot/><Q c={3} t="Charts unconfirmed" s="past cutoff · auto-confirm at 11 PM" h="/staff/charts" hot/><Q c={4} t="Claims & ownership transfers" s="2 claims · 2 transfers awaiting OTP" h="/staff/ownership" hot/><Q c={7} t="Special poojas to fulfil" s="14 Sept Ganapathi Homam · 22 seats" h="/staff/special"/><Q c={1} t="Payout batch ready" s="₹46,300 · 38 temples · 9 manual NEFT" h="/staff/payouts"/><Q c={4} t="Wallet withdrawals" s="₹19,840 · agents & dealers" h="/staff/withdrawals"/><Q c={2} t="Offline payments to confirm" s="1 sponsorship, 1 plan" h="/staff/sponsors"/><Q c={1} t="Restore request" s="Vengamala — pooja list as of 1 Aug" h="/staff/backup"/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Today</h3><Table head={['Metric','Value']} rows={[['Bookings / donations / special / service','142 / 9 / 12 / 5'],['Gateway split','Razorpay 118 · PayU 9 · Stripe 4 · Omniware (own) 37'],['Failed payments','6 (retry links sent)'],['Chatbot conversations','214 · 31 handed to WhatsApp support'],['Backup','Last full backup 02:10 today · OK']]}/></div></SShell>)
}

export function SAnalytics() {
  const traffic=analytics.traffic.map(([m,v,u])=>({m,visits:v,users:u})); const bk=analytics.bookings.map(([d,n])=>({d,n}))
  const C=['#E8722A','#25D366','#4A3527','#C99A3C']
  return (<SShell><H t="Analytics" s="Google Analytics 4 · Play/App Store · WhatsApp (Libromi) · TempleAddress DB" right={<Select options={['Last 30 days','Last 90 days','This year']}/>}/>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat v="44.2k" l="site sessions (GA4)" delta="+14% MoM"/><Stat v="13.8k" l="active users"/><Stat v="6,120" l="app installs (Android 5,340 · iOS 780)" delta="+412 this month"/><Stat v="2,930" l="new WhatsApp users" delta="+18% MoM"/></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3">
      <div className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><Globe size={16}/><h3 className="font-semibold">Traffic — sessions vs users (thousands)</h3></div><div className="mt-3 h-56"><ResponsiveContainer><LineChart data={traffic}><CartesianGrid stroke="#F1E7D8"/><XAxis dataKey="m" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Line isAnimationActive={false} type="monotone" dataKey="visits" stroke="#E8722A" strokeWidth={2.5} dot={false}/><Line isAnimationActive={false} type="monotone" dataKey="users" stroke="#4A3527" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></div>
      <div className="card p-5"><h3 className="font-semibold">Booking channel</h3><div className="h-56"><ResponsiveContainer><PieChart><Pie data={analytics.channels} dataKey="value" nameKey="name" innerRadius={50} outerRadius={80} isAnimationActive={false}>{analytics.channels.map((_,i)=><Cell key={i} fill={C[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="flex flex-wrap gap-2 text-xs">{analytics.channels.map((c,i)=><span key={c.name} className="flex items-center gap-1"><span className="h-2.5 w-2.5 rounded-full" style={{background:C[i]}}/>{c.name} {c.value}%</span>)}</div></div>
      <div className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><TrendingUp size={16}/><h3 className="font-semibold">Bookings by weekday</h3></div><div className="mt-3 h-48"><ResponsiveContainer><BarChart data={bk}><CartesianGrid stroke="#F1E7D8" vertical={false}/><XAxis dataKey="d" tick={{fontSize:12}}/><YAxis tick={{fontSize:12}}/><Tooltip/><Bar isAnimationActive={false} dataKey="n" fill="#E8722A" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div>
      <div className="card p-5"><h3 className="font-semibold">Top pages (GA4)</h3><Table head={['Page','Views']} rows={[['/t/kottur-sree-mahavishnu-temple','8,420'],['/special','6,130'],['/t/thrikapaleshwaram-temple','4,910'],['/festival','3,220'],['/sponsor','1,040']]}/></div>
    </div>
    <div className="mt-5 grid gap-5 md:grid-cols-3"><div className="card p-5"><div className="flex items-center gap-2"><Smartphone size={16}/><b>App</b></div><Table head={['Metric','Value']} rows={[['Installs (30d)','412'],['DAU / MAU','1,140 / 4,320'],['Crash-free','99.4%'],['Store rating','4.6 ★ (318)']]}/></div><div className="card p-5"><div className="flex items-center gap-2"><MessageCircle size={16}/><b>WhatsApp (Libromi)</b></div><Table head={['Metric','Value']} rows={[['New users (30d)','2,930'],['Bookings via bot','1,204'],['Chart confirmations','98% within 1 h'],['Template delivery','99.1%']]}/></div><div className="card p-5"><div className="flex items-center gap-2"><Sparkles size={16}/><b>Assistant</b></div><Table head={['Metric','Value']} rows={[['Conversations (30d)','6,410'],['Answered from TA data','84%'],['Handed to support','9%'],['Led to a booking','21%']]}/></div></div></SShell>)
}

export function SListing() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="Sree Neelakeshi Mudippura Temple" s="Submitted by Jinsha (JIN-4471) · 9 Sept" right={<Pill tone="warn">Pending</Pill>}/>
    <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5">
      <div className="card p-5"><h3 className="font-semibold">Completeness</h3><div className="mt-2 flex flex-wrap gap-2">{[['Basics',1],['Location',1],['About',1],['Story',1],['History',0],['Speciality',1],['Guidelines',0],['Remarks',1],['Nearby',1],['Deities',1],['Photos (3)',1],['Contact',1]].map(([n,ok])=><Pill key={n} tone={ok?'ok':'err'}>{ok?<Check size={12}/>:'✕'} {n}</Pill>)}</div><p className="mt-2 text-xs text-brown-500">History and Guidelines are empty — ask the agent, or verify with a note.</p></div>
      <div className="card p-5"><h3 className="font-semibold">Submitted details</h3><Table head={['Field','Value','']} rows={[['Name (EN)','Sree Neelakeshi Mudippura Temple','Edit'],['Name (ML)',<span className="ml">ശ്രീ നീലകേശി മുടിപ്പുര ക്ഷേത്രം</span>,'Edit'],['Deity','Bhagavathi (Neelakeshi) · Ganapathi, Naga','Edit'],['District','Thiruvananthapuram','Edit'],['Address','Mudippura, Vellanad PO – 695543','Edit'],['About','Village Bhagavathi temple known for Mudippura festival in Meenam…','Edit'],['Nearby','Neyyar dam (14 km), Agasthyakoodam base (22 km)','Edit'],['Contact','+91 98… 3312 (Secretary)','Edit']]}/></div>
      <div className="card p-5"><h3 className="font-semibold">Checks</h3><div className="mt-2 space-y-2"><Toggle label="Not a duplicate (nearest: Vellanad Devi Temple, 3.1 km)" defaultChecked/><br/><Toggle label="Photos show the temple exterior" defaultChecked/><br/><Toggle label="Phone verified by call"/></div></div></div>
      <aside className="card space-y-3 p-5"><button onClick={()=>toast('Verified — page live, bookings off until KYC')} className="btn-p w-full">Verify & publish</button><button className="btn-s w-full">Ask agent for changes</button><button className="btn w-full bg-red-50 text-red-700">Reject</button><textarea className="input" rows={3} placeholder="Note to agent"/><p className="text-xs text-brown-500">On verify: agent gets ₹100 (pending 15 days), dealer ₹20. The secretary receives a WhatsApp invite to claim the page and set poojas & KYC.</p></aside></div></SShell>)
}
export function SKyc() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="KYC review"/><div className="card p-4"><Table head={['Temple','Submitted','Documents','Payment mode','80G','Action']} rows={[['Vengamala Bhagavathi Temple','9 Sept','Committee letter · PAN · Bank proof','Bank only → manual NEFT','No',<b className="text-saffron-600">Review</b>],['Kunnathumadom Sree Krishna Temple','8 Sept','Committee letter · PAN · Bank proof · 80G cert','Razorpay via TA',<Pill tone="gold">Yes</Pill>,<b className="text-saffron-600">Review</b>],['Vizhinjam Sree Bhagavathy Temple','7 Sept','Trust deed · PAN · Omniware MID','Omniware (own)','No',<b className="text-saffron-600">Review</b>],['Vithura Sree Mahadeva Temple','6 Sept','Committee letter only','—','—','Waiting for bank proof']]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Kunnathumadom Sree Krishna Temple</h3><div className="mt-3 grid grid-cols-2 gap-3"><div className="photo aspect-[4/3] rounded-xl p-3 text-xs text-white">Committee resolution.pdf</div><div className="photo aspect-[4/3] rounded-xl p-3 text-xs text-white">80G certificate.pdf</div></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Trust PAN"><Input defaultValue="AAATK9981C"/></Field><Field label="80G reg no."><Input defaultValue="AAATK9981CF20231"/></Field><Field label="Bank"><Input defaultValue="SBI ····7720 · SBIN0070231"/></Field><Field label="Penny-drop name match"><Input defaultValue="KUNNATHUMADOM DEVASWOM — 96%"/></Field></div>
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>toast('KYC approved — bookings on, 80G receipts enabled')} className="btn-p">Approve · enable bookings & 80G</button><button className="btn-s">Approve without 80G</button><button className="btn bg-red-50 text-red-700">Reject</button></div></div></SShell>)
}
export function SCharts() {
  return (<SShell><H t="Charts"/><div className="mb-4 rounded-xl bg-saffron-50 p-3 text-sm text-saffron-800">3 temples haven't confirmed tonight's chart. Auto-confirm runs at 11 PM; devotees are already booked.</div>
    <div className="card p-4"><Table head={['Temple','Date','#','₹','Sent','Status','Action']} rows={[['Kottur Sree Mahavishnu','13 Sept','14','3,420','WhatsApp ✓ Email ✓',<Pill tone="warn">Prepared</Pill>,'Force confirm · Resend'],['Edakkayil Maha Ganapathi','13 Sept','6','740','WhatsApp ✓ Email ✗ bounced',<Pill tone="warn">Prepared</Pill>,'Force confirm · Fix email'],['Vengamala Bhagavathi','13 Sept','2','60','WhatsApp ✓',<Pill tone="warn">Prepared</Pill>,'Force confirm'],['Bilathikulam Sree Shiva','13 Sept','8','1,940','WhatsApp ✓',<Pill tone="ok">Confirmed</Pill>,'View'],['Thrikapaleshwaram','13 Sept','11','2,760','WhatsApp ✓ Email ✓',<Pill tone="ok">Confirmed</Pill>,'View']]}/></div>
    <div className="mt-3 flex gap-2"><button className="btn-s">Prepare now (all)</button><button className="btn-g"><Download size={16}/>Today's PDFs</button></div></SShell>)
}
export function SSpecial() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="Special pooja fulfilment"/><div className="card p-4"><Table head={['Pooja','Date','Temple','Seats','Collected ₹','Temple cost ₹','Margin ₹','Status','Action']} rows={[['Ashta Dravya Maha Ganapathi Homam','14 Sept','Kottur Mahavishnu','22 / 40','33,000','15,000','18,000',<Pill tone="warn">Confirm with temple</Pill>,'Send sankalpam list'],['Pithru Tharpanam','26 Sept','Thrikapaleshwaram','31 / 60','65,100','30,000','35,100',<Pill>Open</Pill>,'—'],['Bhagavathi Seva','12 Sept','Vengamala','9 / 40','6,750','3,500','3,250',<Pill tone="info">Performed</Pill>,<b className="text-saffron-600">Upload proof</b>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Bhagavathi Seva · 12 Sept · upload proof</h3><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{['+ photo','+ photo','+ video','prasadam dispatch'].map(x=><button key={x} className="grid aspect-square place-items-center rounded-xl border-2 border-dashed border-brown-200 text-sm text-brown-500">{x}</button>)}</div><button onClick={()=>toast('Proof sent to 9 devotees on WhatsApp')} className="btn-p mt-4">Send proof to devotees & mark done</button><span className="ml-2 text-xs text-brown-500">Creates vendor payable ₹3,500 to Vengamala.</span></div></SShell>)
}

/* -------- PAYOUTS: manual NEFT sheet flow -------- */
export function SPayouts() {
  const [step,setStep]=useState(1); const [toast,el]=useToast(); const [tab,setTab]=useState(0)
  const rows=[['PO-2637-001','Kottur Sree Mahavishnu','Razorpay via TA','7','12,650','FDRL ····4412 · FDRL0001234'],['PO-2637-002','Thrikapaleshwaram','Razorpay via TA','7','9,120','SBIN ····0192 · SBIN0070231'],['PO-2637-003','Edakkayil Maha Ganapathi','PayU via TA','6','4,780','CNRB ····5531 · CNRB0001120'],['PO-2637-004','Vengamala Bhagavathi','Bank only (manual)','5','2,460','FDRL ····2201 · FDRL0002201'],['PO-2637-005','Vengamala Bhagavathi (special pooja cost)','Bank only (manual)','1','3,500','FDRL ····2201 · FDRL0002201'],['PO-2637-006','Kunnathumadom Sree Krishna','Bank only (manual)','4','1,890','SBIN ····7720 · SBIN0070231'],['…','32 more','','','11,900','']]
  return (<SShell>{el}<H t="Payouts" s="Batch #2026-37 · charts completed 1–7 Sept · 38 temples · ₹46,300" right={<Pill tone="info">Manual NEFT until RazorpayX is added</Pill>}/>
    <Tabs tabs={['This batch','History','Settings']} at={tab} set={setTab}/>
    {tab===0 && <><Steps items={['Batch created','Export Excel','Pay in internet banking','Import UTRs','Marked paid']} at={step}/>
      <div className="mb-4 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900"><b>How this works.</b> Every completed chart creates a payable. On Monday the accountant exports this sheet, uploads it to the bank's bulk-NEFT portal (or pays one by one), then fills the <b>UTR / journal no.</b> column in the same sheet and imports it back. Rows with a UTR are marked <b>Paid</b> and the temple gets a WhatsApp. Custom-gateway temples (Omniware) never appear here.</div>
      <div className="card p-4"><Table head={['Payout ref','Temple','Collected via','Charts','Amount ₹','Beneficiary (A/c · IFSC)']} rows={rows}/></div>
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>{setStep(2);toast('NEFT sheet downloaded: payouts-2026-37.xlsx')}} className="btn-p"><Download size={16}/>Export NEFT Excel</button><button onClick={()=>setStep(3)} className="btn-s"><Upload size={16}/>Import completed sheet</button><button className="btn-g">Mark one as paid</button></div>
      {step>=3 && <div className="card mt-5 p-5"><h3 className="font-semibold">Import preview · payouts-2026-37.xlsx</h3><p className="text-xs text-brown-500">Columns read: payout_ref, amount, utr_or_journal_no, paid_on, remarks</p><div className="mt-3"><Table head={['Payout ref','Temple','₹','UTR / journal','Paid on','Result']} rows={[['PO-2637-001','Kottur Sree Mahavishnu','12,650','FDRLN26251000431','15 Sept',<Pill tone="ok">Will mark paid</Pill>],['PO-2637-002','Thrikapaleshwaram','9,120','—','—',<Pill tone="err">Failed: IFSC invalid</Pill>],['PO-2637-004','Vengamala Bhagavathi','2,460','FDRLN26251000432','15 Sept',<Pill tone="ok">Will mark paid</Pill>],['PO-2637-005','Vengamala Bhagavathi','3,500','FDRLN26251000432','15 Sept',<Pill tone="ok">Will mark paid (same UTR)</Pill>],['PO-2637-006','Kunnathumadom','1,890','JRN-0921-44','15 Sept',<Pill tone="ok">Will mark paid (journal)</Pill>]]}/></div><button onClick={()=>{setStep(4);toast('36 payouts marked paid · temples notified on WhatsApp')}} className="btn-p mt-3"><Check size={16}/>Apply · mark paid</button></div>}</>}
    {tab===1 && <div className="card p-4"><Table head={['Batch','Period','Temples','₹','Exported','Imported','Paid / failed']} rows={[['#2026-36','25–31 Aug','36','44,120','1 Sept','1 Sept','36 / 0'],['#2026-35','18–24 Aug','34','41,860','25 Aug','25 Aug','33 / 1'],['#2026-34','11–17 Aug','31','38,200','18 Aug','19 Aug','31 / 0']]}/></div>}
    {tab===2 && <div className="card grid gap-4 p-5 md:grid-cols-2"><Field label="Payout cycle"><Select options={['Weekly (Monday)','On ₹5,000 threshold','Manual']}/></Field><Field label="Minimum payout ₹"><Input defaultValue="500"/></Field><Field label="Sheet format"><Select options={['Federal Bank bulk NEFT','SBI CINB bulk','Generic (payout_ref, name, acct, ifsc, amount, utr)']}/></Field><Field label="Payout product" hint="When connected, batches are paid automatically; the Excel flow stays as fallback"><Select options={['Manual NEFT (current)','RazorpayX (not connected)','Cashfree Payouts (not connected)']}/></Field></div>}
  </SShell>)
}
export function SWithdrawals() {
  return (<SShell><H t="Wallet withdrawals" s="Same export / import mechanism as temple payouts · wallet debited only when marked paid"/><div className="card p-4"><Table head={['Requested','Who','Role','₹','TDS','Net ₹','Pay to','Status','']} rows={[['11 Sept','Jinsha (JIN-4471)','Agent','6,840','342','6,498','UPI jinsha@okaxis',<Pill tone="warn">Requested</Pill>,<b className="text-emerald-700">Approve</b>],['10 Sept','Rahul','Dealer','10,000','500','9,500','FDRL ····9902',<Pill tone="warn">Requested</Pill>,<b className="text-emerald-700">Approve</b>],['9 Sept','Sangeetha (SAN-0932)','Agent','2,000','100','1,900','UPI',<Pill tone="info">In batch</Pill>,'—'],['8 Sept','Arun (ARU-2210)','Agent','1,000','50','950','UPI',<Pill tone="info">In batch</Pill>,'—']]}/></div><div className="mt-3 flex gap-2"><button className="btn-p"><Download size={16}/>Export withdrawal sheet</button><button className="btn-s"><Upload size={16}/>Import UTRs</button></div></SShell>)
}
export function SOwnership() {
  const [toast,el]=useToast()
  return (<SShell>{el}<H t="Claims & ownership transfers"/>
    <div className="card p-5"><h3 className="font-semibold">Claims</h3><Table head={['Temple','Claimant','Role','Current owner','Docs','Phone check','Action']} rows={[['Vengamala Bhagavathi Temple','Suresh P','Secretary','Agent Jinsha','Resolution ✓ · PAN ✓ · ID ✓',<Pill tone="ok">Matches listed no.</Pill>,<button onClick={()=>toast('Claim approved — ownership moved to Suresh P')} className="btn-p !py-1.5 text-xs">Approve</button>],['Edakkayil Maha Ganapathi','Anitha R','Treasurer','Unclaimed','Resolution ✓ · PAN ✗',<Pill tone="warn">Different number</Pill>,<button className="btn-g !py-1.5 text-xs">Call & verify</button>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Transfers awaiting acceptance</h3><Table head={['Temple','From','To','Reason','Requested','Status']} rows={[['Thrikapaleshwaram Temple','Gopan (Secretary)','Ravi (new Secretary)','Committee election','10 Sept',<Pill tone="warn">OTP not yet accepted</Pill>],['Bilathikulam Sree Shiva','Committee','Devaswom board','Devaswom takeover','9 Sept',<Pill tone="warn">Docs under review</Pill>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Audit log</h3><Table head={['Date','Listing','Event','By']} rows={[['2 Aug','Kottur Sree Mahavishnu','Owner: agent Jinsha → Nishanth K (claim)','Staff Anand'],['14 Jul','Prasad Nambeesan (service)','Owner set at signup','System'],['9 Jul','Kottur Sree Mahavishnu','Verified','Staff Anand']]}/></div></SShell>)
}
export function SSponsors() {
  return (<SShell><H t="Sponsors & plans"/><div className="card p-5"><h3 className="font-semibold">Offline payments to confirm</h3><Table head={['Date','Payer','For','₹','Method','Ref','']} rows={[['10 Sept','Malabar Gold Traders','Sponsor Patron → Edakkayil Maha Ganapathi','35,400','Bank transfer','UTR FDRLN262…',<b className="text-emerald-700">Confirm & activate</b>],['9 Sept','Thrikapaleshwaram Committee','Temple Basic renewal','6,000','Cheque','#004112',<b className="text-emerald-700">Confirm & activate</b>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Active subscriptions</h3><Table head={['Subscriber','Plan','Sponsored by','Start','Expiry','GST inv.','Status']} rows={[['Kottur Sree Mahavishnu','Pro','Resurge India Foundation (Patron)','1 Aug 2026','31 Jul 2027','INV-0412',<Pill tone="ok">Active</Pill>],['Thrikapaleshwaram','Basic','—','28 Sept 2025','28 Sept 2026','INV-0298',<Pill tone="warn">Expires in 17 days</Pill>],['Prasad Nambeesan','Service Pro','—','4 Oct 2025','4 Oct 2026','INV-0301',<Pill tone="warn">Expires in 23 days</Pill>],['Bilathikulam Sree Shiva','Basic','—','1 Jun 2026','31 May 2027','INV-0388',<Pill tone="ok">Active</Pill>]]}/></div></SShell>)
}
export function SBackup() {
  return (<SShell><H t="Backup & restore"/><div className="grid grid-cols-3 gap-3"><Stat v="02:10 today" l="last full backup · OK"/><Stat v="30 days" l="retention · off-site"/><Stat v="12 Jun" l="last restore drill · passed"/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Restore requests</h3><Table head={['Temple','Requested by','What','Point in time','Status','']} rows={[['Vengamala Bhagavathi','Secretary (+91 98…) · verified by call','Pooja list & prices','1 Aug 2026',<Pill tone="warn">Verify identity</Pill>,<span><b className="text-emerald-700">Run restore</b> · Reject</span>]]}/></div>
    <div className="card mt-5 p-5"><h3 className="font-semibold">Export jobs</h3><Table head={['Temple','Type','Started','Size','Status']} rows={[['Kottur Sree Mahavishnu','Monthly auto','1 Sept 02:30','18 MB',<Pill tone="ok">Delivered</Pill>],['Edakkayil Maha Ganapathi','On request','11 Sept 10:02','9 MB',<Pill tone="info">Running</Pill>]]}/></div></SShell>)
}
export function SConfig() {
  const [tab,setTab]=useState(0); const [toast,el]=useToast(); const [maint,setMaint]=useState(false)
  const feeRow=(t,m,v,r)=>[t,<Select options={['Off','Percent','Fixed','Percent + fixed']} defaultValue={m}/>,<Input defaultValue={v} className="input !w-20"/>,<Select options={['Devotee','Temple']}/>,<Select options={['Yes','No']} defaultValue={r}/>,'18%']
  return (<SShell>{el}<H t="Configuration" s="Portal admin only — approvals, KYC & fee policy, and platform-wide switches"/><Tabs tabs={['Convenience fee','Payment gateways','Plans','Agent rates','Chatbot','General']} at={tab} set={setTab}/>
    {tab===0 && <div className="card p-5"><h3 className="font-semibold">Platform defaults (used when a listing says “inherit”)</h3><div className="mt-3"><Table head={['Transaction type','Mode','Value','Who pays','Refundable','GST on fee']} rows={[feeRow('Vazhipadu','Off','0','Yes'),feeRow('Donation','Off','0','Yes'),feeRow('Special pooja','Percent','2','No'),feeRow('Service','Off','0','Yes')]}/></div><div className="mt-3 rounded-xl bg-saffron-50 p-3 text-sm text-saffron-800">Resolution: <b>listing override → platform default → 0</b>. 3 listings currently override.</div><button onClick={()=>toast('Defaults saved')} className="btn-p mt-3">Save defaults</button></div>}
    {tab===1 && <div className="card p-5"><h3 className="font-semibold">Platform gateway accounts</h3><p className="text-sm text-brown-500">Temples pick which of these to offer (or use their own).</p><div className="mt-3"><Table head={['Gateway','Mode','Customer fee bearer','Webhook','Status','']} rows={[['Razorpay','Platform account · default','Enabled','/api/payments/webhooks/razorpay/ ✓',<Pill tone="ok">Live</Pill>,'Keys'],['PayU','Platform account','Enabled','/api/payments/webhooks/payu/ ✓',<Pill tone="ok">Live</Pill>,'Keys'],['Stripe','Platform account · international','Absorbed · shown as line','/api/payments/webhooks/stripe/ ✓',<Pill tone="ok">Live</Pill>,'Keys'],['Omniware (Federal Bank)','Temple\'s own account (custom)','Per temple','/api/payments/webhooks/omniware/{listing} ✓',<Pill tone="ok">Live</Pill>,'—'],['RazorpayX (payouts)','Not connected','—','—',<Pill>Planned</Pill>,'Connect']]}/></div><div className="mt-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">Custom-gateway listings are excluded from payables and payouts automatically. Bank-only listings go to the manual NEFT sheet.</div></div>}
    {tab===2 && <div className="card p-5"><Table head={['Plan','₹/yr','White-label','Custom domain','WhatsApp chart','Admin phones','Self backup','Ads off']} rows={[['Free','0','—','—','—','1','On request','—'],['Temple Basic','6,000','—','—','✓','1','✓','✓'],['Temple Pro','15,000','✓','✓','✓','3','✓ monthly','✓'],['Service Pro','3,000','—','—','✓','1','✓','✓'],['Sponsor Supporter / Patron / Benefactor','15k / 30k / 50k','grants Pro to temple','','','','','']]}/><button className="btn-s mt-3">Edit plans</button></div>}
    {tab===3 && <div className="card p-5"><Table head={['Event','Agent','Dealer','Hold']} rows={[['Listing approved','₹100','₹20','15 days'],['KYC + bookings on','₹200','₹40','15 days'],['Plan paid (first year)','15%','5%','15 days'],['Sponsorship (ex-GST)','15%','5%','15 days'],['Renewal','5%','2%','15 days'],['Special pooja via link','5%','—','after pooja + 15 days'],['Fee revenue from agent\'s listing','10% (12 mo)','3%','monthly']]}/><div className="mt-3 grid gap-4 md:grid-cols-2"><Field label="Minimum withdrawal ₹"><Input defaultValue="500"/></Field><Field label="Withdrawal cycle"><Select options={['Monthly (last working day)','Weekly']}/></Field></div><button className="btn-p mt-3">Save</button></div>}
    {tab===4 && <div className="card grid gap-4 p-5 md:grid-cols-2"><Field label="Model provider" hint="Swappable; the bot only reads TempleAddress data"><Select options={['OpenAI-compatible','Gemini','Local (Ollama)']}/></Field><Field label="Knowledge sources"><Select options={['Listings + poojas + festivals + FAQs (default)','Listings only']}/></Field><Field label="Escalate to WhatsApp support when"><Select options={['Confidence < 0.6 or booking/refund intent','Never']}/></Field><Field label="Languages"><Select options={['English + Malayalam','English']}/></Field><Field label="System prompt" className="md:col-span-2"><textarea className="input" rows={3} defaultValue="You are the TempleAddress assistant. Answer only from the provided temple data. Never invent timings or prices. Offer to start a booking when relevant."/></Field><button className="btn-p">Save</button></div>}
    {tab===5 && <div className="space-y-5">
      <div className="card grid gap-4 p-5 md:grid-cols-2"><Field label="Default chart cutoff"><Select options={['7:00 PM','8:00 PM','9:00 PM']} defaultValue="8:00 PM"/></Field><Field label="Auto-confirm unconfirmed charts at"><Select options={['10:00 PM','11:00 PM','Never']} defaultValue="11:00 PM"/></Field><Field label="Booking window (days ahead)"><Input defaultValue="30"/></Field><Field label="GST % on TA services"><Input defaultValue="18"/></Field><Field label="Google Analytics 4 property"><Input defaultValue="G-TA2026KL"/></Field><Field label="WhatsApp provider"><Input defaultValue="Libromi · +91 9495 041196"/></Field><Field label="Backup retention (days)"><Input defaultValue="30"/></Field><Field label="Platform convenience fee — global cap %" hint="Ceiling a listing's override cannot exceed"><Input defaultValue="5"/></Field><button onClick={()=>toast('General settings saved')} className="btn-p self-end">Save</button></div>
      <div className="card p-5"><h3 className="font-semibold">Staff, accountant & dealer approvals</h3><p className="text-sm text-brown-500">New staff, accountant and dealer accounts stay disabled until a Portal admin approves them here.</p>
        <div className="mt-3"><Table head={['Name','Requested role','Requested','Action']} rows={[['Deepa Menon','Accountant','10 Sept',<span><b className="text-emerald-700">Approve</b> · Reject</span>],['Vishnu R','Moderator','9 Sept',<span><b className="text-emerald-700">Approve</b> · Reject</span>],['Kozhikode East — new dealer','Dealer','8 Sept',<span><b className="text-emerald-700">Approve</b> · Reject</span>]]}/></div></div>
      <div className="card p-5"><h3 className="font-semibold">Manual triggers</h3><p className="text-sm text-brown-500">Force actions the schedule would otherwise run automatically.</p>
        <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>toast('Daily chart generation triggered for all open temples')} className="btn-g"><CalendarCheck size={16}/>Trigger today's charts now</button><button onClick={()=>toast('Payout batch generation triggered')} className="btn-g"><Landmark size={16}/>Trigger payout batch now</button><button onClick={()=>toast('Full backup started')} className="btn-g"><Database size={16}/>Run backup now</button></div></div>
      <div className={`card p-5 ${maint?'ring-2 ring-red-400':''}`}><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Site maintenance mode</h3><p className="text-sm text-brown-500">Shows a maintenance page to devotees; staff and vendor dashboards stay reachable. Use for deployments or emergency fixes.</p></div><Toggle label={maint?'Maintenance ON':'Off'} defaultChecked={maint} onChange={v=>{setMaint(v);toast(v?'Maintenance mode enabled — public site now shows the maintenance page':'Maintenance mode disabled — site is live')}}/></div>{maint&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">Public site is currently showing a maintenance page. Remember to turn this off before devotees are affected for long.</div>}</div>
    </div>}
  </SShell>)
}
export function STables() {
  return (<SShell><H t="Advanced · tables" s="Raw table browser for support and finance. Day-to-day work happens in the queues."/><input placeholder="Search tables…" className="input mb-4 !w-72"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Listings','1,304'],['Poojas','9,812'],['Bookings','38,411'],['Donations','2,190'],['PaymentTransactions','41,020'],['DailyCharts','6,730'],['VendorPayables','6,690'],['VendorPayouts','1,118'],['Subscriptions','214'],['Sponsors','61'],['Agents','190'],['Dealers','14'],['Wallets','204'],['WalletTransactions','3,301'],['OwnershipEvents','412'],['ExportJobs','412']].map(([t,n])=><div key={t} className="card p-4"><b className="text-sm">{t}</b><div className="text-xs text-brown-500">{n} rows</div></div>)}</div></SShell>)
}
